<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#4.-Composite-Types-(II)" data-toc-modified-id="4.-Composite-Types-(II)-1">4. Composite Types (II)</a></span><ul class="toc-item"><li><span><a href="#4.4-Structs" data-toc-modified-id="4.4-Structs-1.1">4.4 Structs</a></span><ul class="toc-item"><li><span><a href="#Recursive-Data-Structures" data-toc-modified-id="Recursive-Data-Structures-1.1.1">Recursive Data Structures</a></span></li><li><span><a href="#Struct-Literals" data-toc-modified-id="Struct-Literals-1.1.2">Struct Literals</a></span></li><li><span><a href="#command-line-arguments" data-toc-modified-id="command-line-arguments-1.1.3">command-line-arguments</a></span></li><li><span><a href="#Comparing-Structs" data-toc-modified-id="Comparing-Structs-1.1.4">Comparing Structs</a></span></li><li><span><a href="#Struct-Embedding-and-Anonymous-Fields" data-toc-modified-id="Struct-Embedding-and-Anonymous-Fields-1.1.5">Struct Embedding and Anonymous Fields</a></span></li><li><span><a href="#Use-one-of-the-two-forms" data-toc-modified-id="Use-one-of-the-two-forms-1.1.6">Use one of the two forms</a></span></li></ul></li><li><span><a href="#4.5-JSON" data-toc-modified-id="4.5-JSON-1.2">4.5 JSON</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#github-HTTP-request" data-toc-modified-id="github-HTTP-request-1.2.0.1">github HTTP request</a></span></li><li><span><a href="#github-api-for-issues" data-toc-modified-id="github-api-for-issues-1.2.0.2">github api for issues</a></span></li></ul></li></ul></li><li><span><a href="#4.6-Text-and-HTML-Templates" data-toc-modified-id="4.6-Text-and-HTML-Templates-1.3">4.6 Text and HTML Templates</a></span></li></ul></li></ul></div>

# 4. Composite Types (II)
*    **Structs**
     *    Struct Literals
     *    Comparing Structs
     *    Struct Embedding and Anonymous Fields
*    JSON
*    Text and HTML Templates


## 4.4 Structs

* A struct is an aggregate data type grouping together zero or more named values of arbitrary types as a single entity
* Each value is called a field
* The name of a struct field is exported if it begins with a capital letter; this is Go's main access control mechanism
* A struct type may contain a mixture of exported and unexported fields

<code>
type struct_name struct {
  member1 datatype;
  member2 datatype;
  member3 datatype;
  ...
}
</code>

In [35]:
//Employee
import "fmt"
import "time"
type Employee struct {
    ID int
    Name string
    Address string
    DoB time.Time //date of birth
    Position string
    Salary int
    ManagerID int
}
func main(){
     
    alan := Employee{ID:1, ManagerID: 3, Position: "Vice President"}
    dilbert := Employee{ID:2, ManagerID: 1}
      
    employeeDB := make(map[int]*Employee)
    employeeDB[alan.ID] = &alan 
    employeeDB[dilbert.ID] = &dilbert
    
    fmt.Printf("employeeDB: %q\n",employeeDB)
    for _,emp := range employeeDB {
        fmt.Printf("emp: %q\n",emp)
        fmt.Println((*emp).ID, emp.Position)
    }
}

employeeDB: map['\x01':%!q(*main.Employee=&{1   {0 0 <nil>} Vice President 0 3}) '\x02':%!q(*main.Employee=&{2   {0 0 <nil>}  0 1})]
emp: &{'\x01' "" "" "0001-01-01 00:00:00 +0000 UTC" "Vice President" '\x00' '\x03'}
1 Vice President
emp: &{'\x02' "" "" "0001-01-01 00:00:00 +0000 UTC" "" '\x00' '\x01'}
2 


In [36]:
//Employee
import "fmt"
import "time"
type Employee struct {
    ID int
    Name string
    Address string
    DoB time.Time
    Position string
    Salary int
    ManagerID int
}
func main(){
    
    alan := Employee{ID:1, ManagerID: 3, Position: "Vice President"}
    dilbert := Employee{ID:2, ManagerID: 1}
    dilbert.Salary -= 5000  // demoted, for writing too few lines of code
    position := &dilbert.Position
    *position = "Senior" + *position //promoted, for outsourcing to Elbonia
    
    var employeeOfTheMonth *Employee = &dilbert
    employeeOfTheMonth.Position += " (proactive team player)"
    //(*employeeOfTheMonth).Position
    //(*employeeOfTheMonth).Position += " (proactive team player)"
    // employeeOfTheMonth.Position and (*employeeOfTheMonth).Position are equivalent
    
    employeeDB := make(map[int]*Employee)
    employeeDB[alan.ID] = &alan
    employeeDB[dilbert.ID] = &dilbert
    
    fmt.Printf("%q\n",employeeDB)
    for _,emp := range employeeDB {
        fmt.Printf("%q\n",emp)
    }
}

map['\x01':%!q(*main.Employee=&{1   {0 0 <nil>} Vice President 0 3}) '\x02':%!q(*main.Employee=&{2   {0 0 <nil>} Senior (proactive team player) -5000 1})]
&{'\x01' "" "" "0001-01-01 00:00:00 +0000 UTC" "Vice President" '\x00' '\x03'}
&{'\x02' "" "" "0001-01-01 00:00:00 +0000 UTC" "Senior (proactive team player)" '�' '\x01'}


In [37]:
import "fmt"
var employeeDB map[int]*Employee
//func EmployeeByID(id int) Employee { return *employeeDB[id]}
func EmployeeByID(id int) *Employee { return employeeDB[id]}

func main() {
    alan := Employee{ID:1, ManagerID: 3, Position: "Vice President"}
    employeeDB = make(map[int]*Employee)
    employeeDB[alan.ID] = &alan
    dilbert := Employee{ID:2, ManagerID: 1}
    employeeDB[dilbert.ID] = &dilbert
    
    fmt.Println(EmployeeByID(dilbert.ManagerID).Position) // "boss"
    id := dilbert.ID    
    EmployeeByID(id).Salary = 0  //dilbert is fired
                                 //Should return *Employee, to be in left-hand-side
}

Vice President


### Recursive Data Structures
* Struc type ***S*** can't declare a field of the same type ***S***
  * aggregate value cannot containt itself
* S may declare a field of the pointer type \****S***
  * create recursive data structure like lists and trees
* Implement an insertion sort in the following

In [29]:
//gopl.io/ch4/treesort

// Copyright © 2016 Alan A. A. Donovan & Brian W. Kernighan.
// License: https://creativecommons.org/licenses/by-nc-sa/4.0/

import ("math/rand";"sort";"fmt")  
type tree struct {
	value       int
	left, right *tree
}

// Sort sorts values in place.
func Sort(values []int) {
	var root *tree
	for _, v := range values {
		root = add(root, v)
	}
	appendValues(values[:0], root) // append in the slice, the first position
    //appendValues(values, root)     // append in the last position
    //appendValues(values[:], root)    // append in the last position
}

// appendValues appends the elements of t to values in order
// and returns the resulting slice.
func appendValues(values []int, t *tree) []int {
    fmt.Println(values,"len",len(values),cap(values))
	if t != nil {
		values = appendValues(values, t.left)
		values = append(values, t.value)
		values = appendValues(values, t.right)
	}
	return values
}

func add(t *tree, value int) *tree {
	if t == nil {
		// Equivalent to return &tree{value: value}.
		t = new(tree)
		t.value = value
		return t
	}
	if value < t.value {
		t.left = add(t.left, value)
	} else {
		t.right = add(t.right, value)
	}
	return t
}

func main(){
    data := make([]int, 50)
    for i := range data {
        data[i] = rand.Int() % 50
    }
    
	//treesort.Sort(data)
    fmt.Println(data)
    Sort(data)
//sort.Ints(data)
    if !sort.IntsAreSorted(data) {
		fmt.Printf("not sorted: %v", data)
    } else {
        fmt.Printf("sorted: %v", data)
    }
}
//!-

[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 35 27 46 46 10 3 5 32 47 26 30 7]
[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 35 27 46 46 10 3 5 32 47 26 30 7] len 50 50
[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 35 27 46 46 10 3 5 32 47 26 30 7] len 50 50
[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 35 27 46 46 10 3 5 32 47 26 30 7] len 50 50
[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 35 27 46 46 10 3 5 32 47 26 30 7] len 50 50
[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 35 27 46 46 10 3 5 32 47 26 30 7 1] len 51 112
[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 3

[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 35 27 46 46 10 3 5 32 47 26 30 7 1 1 1 2 2 2 3 5 5 6 7 7 10 11 11 12 12 15 16 18 18 19 19 21 22 23 23 26 27 28 30] len 81 112
[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 35 27 46 46 10 3 5 32 47 26 30 7 1 1 1 2 2 2 3 5 5 6 7 7 10 11 11 12 12 15 16 18 18 19 19 21 22 23 23 26 27 28 30 31] len 82 112
[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 35 27 46 46 10 3 5 32 47 26 30 7 1 1 1 2 2 2 3 5 5 6 7 7 10 11 11 12 12 15 16 18 18 19 19 21 22 23 23 26 27 28 30 31] len 82 112
[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 35 27 46 46 10 3 5 32 47 26 30 7 1 1 1 2 2 2 3 5 5 6 7 7 10 11 11 12 12 15 16 18 18 19 19 21 22 23 23 26 27 28 30 31 32] len 83 112
[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 4

[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 35 27 46 46 10 3 5 32 47 26 30 7 1 1 1 2 2 2 3 5 5 6 7 7 10 11 11 12 12 15 16 18 18 19 19 21 22 23 23 26 27 28 30 31 32 34 34 35 37 38 39 39 41 42 43 44 44 46 46 47] len 98 112
[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 35 27 46 46 10 3 5 32 47 26 30 7 1 1 1 2 2 2 3 5 5 6 7 7 10 11 11 12 12 15 16 18 18 19 19 21 22 23 23 26 27 28 30 31 32 34 34 35 37 38 39 39 41 42 43 44 44 46 46 47 47] len 99 112
[34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 35 27 46 46 10 3 5 32 47 26 30 7 1 1 1 2 2 2 3 5 5 6 7 7 10 11 11 12 12 15 16 18 18 19 19 21 22 23 23 26 27 28 30 31 32 34 34 35 37 38 39 39 41 42 43 44 44 46 46 47 47 49] len 100 112
not sorted: [34 19 23 39 43 38 23 34 22 1 44 7 12 12 21 18 18 31 15 16 41 1 11 1 6 5 28 11 19 47 2 44 37 49 2 42 39 2 35 27 46 46 10 3 5 32 4

<strike>$go get gopl.io/ch4/treesort</strike>
```
$go build gopl.io/ch4/treesort
$go install gopl.io/ch4/treesort
$go test gopl.io/ch4/treesort
```

In [30]:
//!go get gopl.io/ch4/treesort
//!go install gopl.io/ch4/treesort
!go test gopl.io/ch4/treesort -v

=== RUN   TestSort
--- PASS: TestSort (0.00s)
PASS
ok  	gopl.io/ch4/treesort	(cached)


### Struct Literals

* A value of a struct type can be written using a struct literal specifying values for its fields
* There are two forms of struct literal
* The first form requires a value be specified for every field, in the right order
* The second form is used, in which a struct value is initialized by listing some or all of the field names and their corresponding values
* The two forms cannot be mixed in the same literal

In [37]:
import "image/gif"
type Point struct{ X, Y int}
func main(){
  p := Point{1,2} // the first form
  q := Point{Y:2} // the second form
  fmt.Println(p,q)
  
  nframes := 30
  anim := gif.GIF{LoopCount: nframes}
  _ = anim
  fmt.Println(anim)
  fmt.Printf("%#v",anim)
}

//!go doc gif.Gif

{1 2} {0 2}
{[] [] 30 [] {<nil> 0 0} 0}
gif.GIF{Image:[]*image.Paletted(nil), Delay:[]int(nil), LoopCount:30, Disposal:[]uint8(nil), Config:image.Config{ColorModel:color.Model(nil), Width:0, Height:0}, BackgroundIndex:0x0}

```
package p
type T struct{ a, b int} // a and b are not exported

in p/p.go

package main
import "example.com/p"
func main(){
var _ = p.T{a:1, b:2} //compile error, can't reference a  and b 
}

in notexported.go
```

In [5]:
!go mod edit -replace example.com/p=./p 
!go build notexported.go 

# command-line-arguments
./notexported.go:4:14: cannot refer to unexported field a in struct literal of type p.T
./notexported.go:4:19: cannot refer to unexported field b in struct literal of type p.T
exit status 1


go build notexported.go 
### command-line-arguments
./notexported.go:4:14: cannot refer to unexported field a in struct literal of type p.T

./notexported.go:4:19: cannot refer to unexported field b in struct literal of type p.T

In [38]:
//Struct values can be passed as arguments to functions and returned from them
type Point struct{ X, Y int}
func Scale(p Point, factor int) Point {
    return Point{p.X * factor, p.Y * factor}
}

%%
fmt.Println(Scale(Point{1,2},5)) // {5,10}
//Scale(Point{1,2},6).X = 10

{5 10}


In [39]:
//Larger struct types are passsed to or returned from functions indirectly using a pointer
//and this is required if the function must modify the argument
import "time"
type Employee struct {
    ID int
    Name string
    Address string
    DoB time.Time
    Position string
    Salary int
    ManagerID int
} 
func Bonus(e *Employee, percent int) int {
    return e.Salary * percent / 100
}
func AwardAnnualRaise(e *Employee) {
    e.Salary = e.Salary * 105 / 100
}

In [42]:
//two are equivalent
type Point struct{ X, Y int}
%%
pp := &Point{1,2}
fmt.Println(*pp,pp)


{1 2} &{1 2}


In [9]:
type Point struct{ X, Y int}
%%
pp := new(Point)
*pp = Point{1,2}
fmt.Println(pp)

&{1 2}


### Comparing Structs
* If all the fields of a struct are comparable, the struct is comparable
* Two expressions of the comparable types may be compared using == or !!=

In [10]:
//comparing two points
type point struct{X, Y int}
%%
p := Point{1,2}
q := Point{3,2}
fmt.Println(p.X == q.X && p.Y == q.Y) // false
fmt.Println(p == q)                   // false

false
false


* Comparable struct types, may be used as the key type of a map

In [11]:
//comparable struct types as map key
type address struct {
    hostname string
    port     int
}
%%
hits := make(map[address]int)
hits[address{"golang.org",443}]++
hits[address{"gopl.io",80}]+= 23
hits[address{"www.nycu.edu.tw",80}]+= 123
fmt.Println(hits)

map[{golang.org 443}:1 {gopl.io 80}:23 {www.nycu.edu.tw 80}:123]


In [12]:
%%
a := []int{0,1,2,3}
fmt.Printf("%p,%p %d,%p %d,%p %d",&a,a[:],len(a[:]),a[:0],len(a[:0]),a[:1],len(a[:1]))

0x1400012e000,0x14000130000 4,0x14000130000 0,0x14000130000 1

### Struct Embedding and Anonymous Fields
* a convenient syntactic shortcut
* use x.f stands for x.d.e.f

In [13]:
type Circle struct {
    X,Y, Radius int
}
type Wheel struct {
    X,Y, Radius, Spokes int
}
%%
var w Wheel
w.X = 8
w.Y = 8
w.Radius = 5
w.Spokes = 20
fmt.Println(w)

{8 8 5 20}


* Factor out their common parts

In [54]:
import "fmt"
type Point struct {
    X, Y int
}
type Circle struct {
    Center Point
    Radius int
}
type Wheel struct {
    Circle Circle
    Spokes int
}
%%
var w Wheel
w.Circle.Center.X = 8
w.Circle.Center.Y = 8
w.Circle.Radius = 5
w.Spokes = 20
fmt.Println(w)

{{{8 8} 5} 20}


* Declare a field with a type but no name
* Such fields are called anonymous fields
* Due to embedding, we can refer to the names at the leaves of the implicit tree without giving the intervening names

In [51]:
//access the anonymous field
type Circle struct {
    Point
    Radius int
}
type Wheel struct {
    Circle 
    Spokes int
}
%%
var w Wheel
w.X = 8    //equivalent to w.Circle.Point.X = 8
w.Circle.Point.X = 8
w.Y = 8    //equivalent to w.Circle.Point.Y = 8
w.Radius = 5 //equivalent to w.Circle.Radius = 5
w.Circle.Radius = 5
w.Spokes = 20 
fmt.Println(w)

{{{8 8} 5} 20}


* There's no corresponding shorthand for the struct literal syntax

In [55]:
%%
w := Wheel{8,8,5,20} 
fmt.Printf("%#v",w)
_ = w

# gonb_fde9ad99 

 

 Cell[55]: Line 2 
 ./main.go:186:13: cannot use 8 (untyped int constant) as Circle value in struct literal
 

func main() {
	flag.Parse()
 w := Wheel{8,8,5,20} 
 fmt.Printf("%#v",w)
	_ = w

 

 

 Cell[55]: Line 2 
 ./main.go:186:17: too many values in struct literal of type Wheel
 

func main() {
	flag.Parse()
 w := Wheel{8,8,5,20} 
 fmt.Printf("%#v",w)
	_ = w

ERROR: failed to run "/opt/homebrew/bin/go build -o /var/folders/4d/tg201k8x6yb81f_lrvt4440m0000gn/T/gonb_fde9ad99/gonb_fde9ad99": exit status 1

In [57]:
%%
w := Wheel{X:8, Y:8, Radius: 5, Spokes: 20}
_ = w

# gonb_fde9ad99 

 

 Cell[57]: Line 2 
 ./main.go:186:13: unknown field X in struct literal of type Wheel
 

func main() {
	flag.Parse()
 w := Wheel{X:8, Y:8, Radius: 5, Spokes: 20}
 _ = w


 

 

 Cell[57]: Line 2 
 ./main.go:186:18: unknown field Y in struct literal of type Wheel
 

func main() {
	flag.Parse()
 w := Wheel{X:8, Y:8, Radius: 5, Spokes: 20}
 _ = w


 

 

 Cell[57]: Line 2 
 ./main.go:186:23: unknown field Radius in struct literal of type Wheel
 

func main() {
	flag.Parse()
 w := Wheel{X:8, Y:8, Radius: 5, Spokes: 20}
 _ = w

ERROR: failed to run "/opt/homebrew/bin/go build -o /var/folders/4d/tg201k8x6yb81f_lrvt4440m0000gn/T/gonb_fde9ad99/gonb_fde9ad99": exit status 1

### Use one of the two forms

In [60]:
//Anonymous Fields
type Point struct {
    X, Y int
}
type Circle struct {
    Point
    Radius int
}
type Wheel struct {
    Circle 
    Spokes int
}
%%
var w Wheel
w = Wheel{Circle{Point{8, 8}, 5}, 20}

w = Wheel{
		Circle: Circle{
			Point:  Point{X: 8, Y: 8},
			Radius: 5,
		},
		Spokes: 20, // NOTE: trailing comma necessary here (and at Radius)
}

//fmt.Printf("%#v\n", w)
//%v	the value in a default format
//	when printing structs, the plus flag (%+v) adds field names
//%#v	a Go-syntax representation of the value
fmt.Printf("%+v\n",w)
	// Output:
	// Wheel{Circle:Circle{Point:Point{X:8, Y:8}, Radius:5}, Spokes:20}

w.X = 42

fmt.Printf("%#v\n", w)
fmt.Printf("%+v\n", w)
	// Output:
	// Wheel{Circle:Circle{Point:Point{X:42, Y:8}, Radius:5}, Spokes:20}
	//!-

{Circle:{Point:{X:8 Y:8} Radius:5} Spokes:20}
main.Wheel{Circle:main.Circle{Point:main.Point{X:42, Y:8}, Radius:5}, Spokes:20}
{Circle:{Point:{X:42 Y:8} Radius:5} Spokes:20}


*  "anonymous" fields have implicit names, we can't have two anonymous fields of the same type
* w.X = 8 //equivalent to w.circle.point.X = 8, but forbidden outside the package

## 4.5 JSON
* JavaScript Object Notation (JSON) is a standard notation for sending and receiving structured information
* Other similar notation: XML, ASN.1, and Google's Protocol Buffers
* API: encoding/json, encoding/xml, encoding/asn1
* basic JSON types are numbers(decimal or scientific notation), booleans(true, false), and strings (sequene of Unicode code points)
* basic JSON types can be combined recursively using JSON arrays and objects
* JSON array is an ordered sequence of values, written as a comma-separated list enclosed in square brackets
* JSON array are used to encode Go arrays and slices
* JSON object is a mapping from strings to values, written as a sequence of name:value pairs separated by commas and surrounded by braces
* JSON objects are used to encode GO maps and structs

Example

type   |value
-------|-----------------------------------
boolean|true
number | -273.15
string |"She said \"Hello, 世界\""
array  | ["gold", "silver", "bronze"]
object |{"year": 1980,<br>"event": "archery",<br>"medals":["gold","silver","brone"]} 

* Gather movie reviews and offer recommendations
* String literals after the Year and Color field are field tags
* Converting Go data structure to JSON by **json.Marshal**
* Only exported fields are marshaled (so, capitalized names for all the Go field names)
* a field tag is a string of metadata associated at compile time with the field of a struct (**Year** changed to **released**)
* Field tag specifies an alternative JSON name for the Go field
* JSON name: total_count, Go field name: TotalCount
* option: no JSON output if the field has the zero value of the type
<code>
  Year int `json:"released"` 
  Color bool `json:"color, omitempty"`
</code>

In [62]:
//gopl.pl/ch4/movie

// Copyright © 2016 Alan A. A. Donovan & Brian W. Kernighan.
// License: https://creativecommons.org/licenses/by-nc-sa/4.0/

import ("encoding/json";"fmt";"log")

type Movie struct {
	Title  string
	Year   int  `json:"released"`
	Color  bool `json:"color,omitempty"`
	Actors []string
}

var movies = []Movie{
	{Title: "Casablanca", Year: 1942, Color: false,
		Actors: []string{"Humphrey Bogart", "Ingrid Bergman"}},
	{Title: "Cool Hand Luke", Year: 1967, Color: true,
		Actors: []string{"Paul Newman"}},
	{Title: "Bullitt", Year: 1968, Color: true,
		Actors: []string{"Steve McQueen", "Jacqueline Bisset"}},
	// ...
}

In [15]:
func main(){		//!+Marshal
		data, err := json.Marshal(movies)
		if err != nil {
			log.Fatalf("JSON marshaling failed: %s", err)
		}
		fmt.Printf("%s\n", data)
}		//!-Ma

[{"Title":"Casablanca","released":1942,"Actors":["Humphrey Bogart","Ingrid Bergman"]},{"Title":"Cool Hand Luke","released":1967,"color":true,"Actors":["Paul Newman"]},{"Title":"Bullitt","released":1968,"color":true,"Actors":["Steve McQueen","Jacqueline Bisset"]}]


* json.MarshalIndent produces neatly indented output
* two arguments: 
  * a prefix for each line of output 
  * a string for each level of indentation
* Inverse operation to marshalling: **json.Unmarshal**

In [16]:
//MarshalIndent	
func main (){
		//!+MarshalIndent
		data, err := json.MarshalIndent(movies, "", "    ")
		if err != nil {
			log.Fatalf("JSON marshaling failed: %s", err)
		}
		fmt.Printf("%s\n", data)
		//!-MarshalIndent

		//!+Unmarshal
		var titles []struct{ Title string 
                            Year   int  `json:"released"`
                            Color  bool `json:"color,omitempty"`
                             Actors []string
                           }
		if err := json.Unmarshal(data, &titles); err != nil {
			log.Fatalf("JSON unmarshaling failed: %s", err)
		}
		fmt.Println(titles) // "[{Casablanca} {Cool Hand Luke} {Bullitt}]"
		//!-Unmarshal
}

[
    {
        "Title": "Casablanca",
        "released": 1942,
        "Actors": [
            "Humphrey Bogart",
            "Ingrid Bergman"
        ]
    },
    {
        "Title": "Cool Hand Luke",
        "released": 1967,
        "color": true,
        "Actors": [
            "Paul Newman"
        ]
    },
    {
        "Title": "Bullitt",
        "released": 1968,
        "color": true,
        "Actors": [
            "Steve McQueen",
            "Jacqueline Bisset"
        ]
    }
]
[{Casablanca 1942 false [Humphrey Bogart Ingrid Bergman]} {Cool Hand Luke 1967 true [Paul Newman]} {Bullitt 1968 true [Steve McQueen Jacqueline Bisset]}]


#### github HTTP request 
* decode the result as JSON
* url.QueryEscape to escape \? and \&

In [63]:
//gopl.io/ch4/github

// Copyright © 2016 Alan A. A. Donovan & Brian W. Kernighan.
// License: https://creativecommons.org/licenses/by-nc-sa/4.0/

import "time"

const IssuesURL = "https://api.github.com/search/issues"

type IssuesSearchResult struct {
	TotalCount int `json:"total_count"`
	Items      []*Issue
}

type Issue struct {
	Number    int
	HTMLURL   string `json:"html_url"`
	Title     string
	State     string
	User      *User
	CreatedAt time.Time `json:"created_at"`
	Body      string    // in Markdown format
}

type User struct {
	Login   string
	HTMLURL string `json:"html_url"`
}


#### github api for issues
* [github issue api](https://api.github.com/search/issues?q=repo:golang/go%20is:open%20json%20decoder)
* struct fields are capitalized for public access even if JSON names are not
* matching process with JSON names and Go struct names is case-insensitive

In [64]:
import ("encoding/json";"fmt";"net/http";"net/url";"strings")

// SearchIssues queries the GitHub issue tracker.
func SearchIssues(terms []string) (*IssuesSearchResult, error) {
	q := url.QueryEscape(strings.Join(terms, " "))
	resp, err := http.Get(IssuesURL + "?q=" + q)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != http.StatusOK {
		resp.Body.Close()
		return nil, fmt.Errorf("search query failed: %s", resp.Status)
	}
    //fmt.Println(resp.Body)
    fmt.Printf("%q",resp.Body)
	var result IssuesSearchResult
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		resp.Body.Close()
		return nil, err
	}
	resp.Body.Close()
	return &result, nil
}

In [65]:
import ("fmt";"log";"os";"gopl.io/ch4/github")
%args repo:golang/go is:open json decoder
func main() {
	result, err := github.SearchIssues(os.Args[1:])
    //t := []string{"repo:golang/go","is:open","json","decoder"}
    //result, err := github.SearchIssues(t)
    //result, err := SearchIssues(t) 
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%d issues:\n", result.TotalCount)
	for i, item := range result.Items {
		fmt.Printf("%d #%-5d %9.9s %.55s\n",i,
			item.Number, item.User.Login, item.Title)
	}
}

96 issues:
0 #69449   gazerro encoding/json: Decoder.Token does not return an error f
1 #48298     dsnet encoding/json: add Decoder.DisallowDuplicateFields
2 #56733 rolandsho encoding/json: add (*Decoder).SetLimit
3 #42571     dsnet encoding/json: clarify Decoder.InputOffset semantics
4 #26946    deuill encoding/json: clarify what happens when unmarshaling i
5 #11046     kurin encoding/json: Decoder internally buffers full input
6 #67525 mateusz83 encoding/json: don't silently ignore errors from (*Deco
7 #6647    btracey x/tools/cmd/godoc: display type kind of each named type
8 #36225     dsnet encoding/json: the Decoder.Decode API lends itself to m
9 #43716 ggaaooppe encoding/json: increment byte counter when using decode
10 #29035    jaswdr proposal: encoding/json: add error var to compare  the 
11 #14750 cyberphon encoding/json: parser ignores the case of member names
12 #61627    nabice x/tools/gopls: feature: CLI syntax for renaming by iden
13 #65691  Merovius encoding/xml: Decode

## 4.6 Text and HTML Templates
* the simplest formatting: Printf
* separate the format from the code 
* **text/template** and **html/template** packages provide a mechanism for substituting the values of variables into a text or HTML template 

* template is a string or file containing one or more portions enclosed in double braces, {{...}}, called actions
* Each action contains an expression in the template language
  * Printing values
  * Selecting struct fields
  * Calling functions and methods
  * Control flow such as if-else, range, and instantiating other templates

In [67]:
// template
import "fmt"
const templ = `{{.TotalCount}} issues:
{{range .Items}}----------------------------------------
Number: {{.Number}}
User:   {{.User.Login}}
Title:  {{.Title | printf "%.64s"}}
Age:    {{.CreatedAt | daysAgo}} days
{{end}}`
%%
fmt.Println(templ)

{{.TotalCount}} issues:
{{range .Items}}----------------------------------------
Number: {{.Number}}
User:   {{.User.Login}}
Title:  {{.Title | printf "%.64s"}}
Age:    {{.CreatedAt | daysAgo}} days
{{end}}


In [68]:
//Parse the template into a suitable internal represntation
import ("time";"text/template";"os")
func daysAgo(t time.Time) int {
    return int(time.Since(t).Hours()/24)
}
%%
report, err := template.New("report").
   Funcs(template.FuncMap{"daysAgo": daysAgo}).
   Parse(templ)
if (err != nil) {
    fmt.Fprintln(os.Stderr,"error")
} else {
    fmt.Printf("%q\n",report)
}

&{"report" %!q(*parse.Tree=&{report report 0x1400011d800 0 {{.TotalCount}} issues:
{{range .Items}}----------------------------------------
Number: {{.Number}}
User:   {{.User.Login}}
Title:  {{.Title | printf "%.64s"}}
Age:    {{.CreatedAt | daysAgo}} days
{{end}} [] <nil> [{8 206  7} {11 24 {{ 2} {0 0  0}] 1 [] map[] 0 0}) %!q(*template.common=&{map[report:0x14000126500] {{0 0} 0 0 {{} 0} {{} 0}} {0} {{0 0} 0 0 {{} 0} {{} 0}} map[daysAgo:0x104fd8b50] map[daysAgo:{0x105048420 0x10507f740 19}]}) "" ""}


In [22]:
// Template fixed at compile time and template.Must handle the error condition
import ("log";"os";"text/template";"time";"gopl.io/ch4/github")
const templ = `{{.TotalCount}} issues:
{{range .Items}}----------------------------------------
Number: {{.Number}}
User:   {{.User.Login}}
Title:  {{.Title | printf "%.64s"}}
Age:    {{.CreatedAt | daysAgo}} days
{{end}}`

func daysAgo(t time.Time) int {
	return int(time.Since(t).Hours() / 24)
}

var report = template.Must(template.New("issuelist").
	Funcs(template.FuncMap{"daysAgo": daysAgo}).
	Parse(templ))

%args repo:golang/go is:open json decoder  
func main() {
	result, err := github.SearchIssues(os.Args[1:])
    //result, err := SearchIssues(os.Args[1:])
	if err != nil {
		log.Fatal(err)
	}
    fmt.Printf("%v\n",result)
	if err := report.Execute(os.Stdout, result); err != nil {
		log.Fatal(err)
	}
}


&{96 [0x140000d20e0 0x140000d2150 0x140000d21c0 0x140000d2230 0x140000d22a0 0x140000d2310 0x140000d2380 0x140000d23f0 0x140000d2460 0x140000d24d0 0x140000d2540 0x140000d25b0 0x140000d2620 0x140000d2690 0x140000d2700 0x140000d2770 0x140000d27e0 0x140000d2850 0x140000d28c0 0x140000d2930 0x140000d29a0 0x140000d2a10 0x140000d2a80 0x140000d2af0 0x140000d2b60 0x140000d2bd0 0x140000d2c40 0x140000d2cb0 0x140000d2d20 0x140000d2d90]}
96 issues:
----------------------------------------
Number: 69449
User:   gazerro
Title:  encoding/json: Decoder.Token does not return an error for incomp
Age:    31 days
----------------------------------------
Number: 48298
User:   dsnet
Title:  encoding/json: add Decoder.DisallowDuplicateFields
Age:    1131 days
----------------------------------------
Number: 56733
User:   rolandshoemaker
Title:  encoding/json: add (*Decoder).SetLimit
Age:    700 days
----------------------------------------
Number: 42571
User:   dsnet
Title:  encoding/json: clarify Decoder.Inpu

In [69]:
// not handle error, if parse error, exceptions occur
%args repo:golang/go is:open json decoder
func main() {
	//!+parse
	report, err := template.New("report").
		Funcs(template.FuncMap{"daysAgo": daysAgo}).
		Parse(templ)
	if err != nil {
		log.Fatal(err)
	}
	//!-parse
	result, err := github.SearchIssues(os.Args[1:])
    //result, err := SearchIssues(os.Args[1:])
	if err != nil {
		log.Fatal(err)
	}
	if err := report.Execute(os.Stdout, result); err != nil {
		log.Fatal(err)
	}
}


96 issues:
----------------------------------------
Number: 69449
User:   gazerro
Title:  encoding/json: Decoder.Token does not return an error for incomp
Age:    31 days
----------------------------------------
Number: 48298
User:   dsnet
Title:  encoding/json: add Decoder.DisallowDuplicateFields
Age:    1131 days
----------------------------------------
Number: 56733
User:   rolandshoemaker
Title:  encoding/json: add (*Decoder).SetLimit
Age:    700 days
----------------------------------------
Number: 42571
User:   dsnet
Title:  encoding/json: clarify Decoder.InputOffset semantics
Age:    1432 days
----------------------------------------
Number: 26946
User:   deuill
Title:  encoding/json: clarify what happens when unmarshaling into a non
Age:    2255 days
----------------------------------------
Number: 11046
User:   kurin
Title:  encoding/json: Decoder internally buffers full input
Age:    3421 days
----------------------------------------
Number: 67525
User:   mateusz834
Title:  e

* html/template use the same API and expression language as text/template
* with HTML, JavaScript, CSS, or URLs

In [70]:
//gopl.io/ch4/issueshtml

// Copyright © 2016 Alan A. A. Donovan & Brian W. Kernighan.
// License: https://creativecommons.org/licenses/by-nc-sa/4.0/

import ("log";"os";"gopl.io/ch4/github";"html/template")
var issueList = template.Must(template.New("issuelist").Parse(`
<h1>{{.TotalCount}} issues</h1>
<table border=1>
<tr style='text-align: left'>
  <th>#</th>
  <th>State</th>
  <th>User</th>
  <th>Title</th>
</tr>
{{range .Items}}
<tr>
  <td><a href='{{.HTMLURL}}'>{{.Number}}</a></td>
  <td>{{.State}}</td>
  <td><a href='{{.User.HTMLURL}}'>{{.User.Login}}</a></td>
  <td><a href='{{.HTMLURL}}'>{{.Title}}</a></td>
</tr>
{{end}}
</table>
`))

In [71]:
%args repo:golang/go is:open json decoder

func main() {
	//result, err := SearchIssues(os.Args[1:])
    result, err := github.SearchIssues(os.Args[1:])
	if err != nil {
		log.Fatal(err)
	}
	if err := issueList.Execute(os.Stdout, result); err != nil {
		log.Fatal(err)
	}
}


<h1>96 issues</h1>
<table border=1>
<tr style='text-align: left'>
  <th>#</th>
  <th>State</th>
  <th>User</th>
  <th>Title</th>
</tr>

<tr>
  <td><a href='https://github.com/golang/go/issues/69449'>69449</a></td>
  <td>open</td>
  <td><a href='https://github.com/gazerro'>gazerro</a></td>
  <td><a href='https://github.com/golang/go/issues/69449'>encoding/json: Decoder.Token does not return an error for incomplete JSON</a></td>
</tr>

<tr>
  <td><a href='https://github.com/golang/go/issues/48298'>48298</a></td>
  <td>open</td>
  <td><a href='https://github.com/dsnet'>dsnet</a></td>
  <td><a href='https://github.com/golang/go/issues/48298'>encoding/json: add Decoder.DisallowDuplicateFields</a></td>
</tr>

<tr>
  <td><a href='https://github.com/golang/go/issues/56733'>56733</a></td>
  <td>open</td>
  <td><a href='https://github.com/rolandshoemaker'>rolandshoemaker</a></td>
  <td><a href='https://github.com/golang/go/issues/56733'>encoding/json: add (*Decoder).SetLimit</a></td>
</tr>

<tr

* [issues.html](http://skhuang.github.io/ch4/issues.html)
<code>
$ go build gopl.io/ch4/issueshtml
$ ./issueshtml repo:golang/go commenter:gopherbot json encoder >issues.html
</code>

In [66]:
//os.Args = []string{"issuehtml","repo:golang/go","3133","10535"}
%args repo:golang/go 3133 10535
func main() {
	//result, err := SearchIssues(os.Args[1:])
    result, err := github.SearchIssues(os.Args[1:])
	if err != nil {
		log.Fatal(err)
	}
	if err := issueList.Execute(os.Stdout, result); err != nil {
		log.Fatal(err)
	}
}


<h1>3 issues</h1>
<table border=1>
<tr style='text-align: left'>
  <th>#</th>
  <th>State</th>
  <th>User</th>
  <th>Title</th>
</tr>

<tr>
  <td><a href='https://github.com/golang/go/issues/3133'>3133</a></td>
  <td>closed</td>
  <td><a href='https://github.com/ukai'>ukai</a></td>
  <td><a href='https://github.com/golang/go/issues/3133'>html/template: escape xmldesc as &amp;lt;?xml</a></td>
</tr>

<tr>
  <td><a href='https://github.com/golang/go/issues/10535'>10535</a></td>
  <td>open</td>
  <td><a href='https://github.com/dvyukov'>dvyukov</a></td>
  <td><a href='https://github.com/golang/go/issues/10535'>x/net/html: void element &lt;link&gt; has child nodes</a></td>
</tr>

<tr>
  <td><a href='https://github.com/golang/go/issues/47148'>47148</a></td>
  <td>closed</td>
  <td><a href='https://github.com/dmitshur'>dmitshur</a></td>
  <td><a href='https://github.com/golang/go/issues/47148'>all: Go 1.15.14 release status</a></td>
</tr>

</table>


[issues2.html](https://skhuang.github.io/ch4/issues2.html)
<code>
$ ./issueshtml repo:golang/go 3133 10535 >issues2.html
</code>

In [166]:
!./ch4/issueshtml/issueshtml repo:golang/go 3133 10535


<h1>3 issues</h1>
<table>
<tr style='text-align: left'>
  <th>#</th>
  <th>State</th>
  <th>User</th>
  <th>Title</th>
</tr>

<tr>
  <td><a href='https://github.com/golang/go/issues/10535'>10535</a></td>
  <td>open</td>
  <td><a href='https://github.com/dvyukov'>dvyukov</a></td>
  <td><a href='https://github.com/golang/go/issues/10535'>x/net/html: void element &lt;link&gt; has child nodes</a></td>
</tr>

<tr>
  <td><a href='https://github.com/golang/go/issues/3133'>3133</a></td>
  <td>closed</td>
  <td><a href='https://github.com/ukai'>ukai</a></td>
  <td><a href='https://github.com/golang/go/issues/3133'>html/template: escape xmldesc as &amp;lt;?xml</a></td>
</tr>

<tr>
  <td><a href='https://github.com/golang/go/issues/47148'>47148</a></td>
  <td>closed</td>
  <td><a href='https://github.com/dmitshur'>dmitshur</a></td>
  <td><a href='https://github.com/golang/go/issues/47148'>all: Go 1.15.14 release status</a></td>
</tr>

</table>


In [167]:
//gopl.io/ch4/autoescape

// Copyright © 2016 Alan A. A. Donovan & Brian W. Kernighan.
// License: https://creativecommons.org/licenses/by-nc-sa/4.0/

import ("fmt";"html/template";"log";"os")

//!+
func main() {
	const templ = `<p>A: {{.A}}</p><p>B: {{.B}}</p>`
	t := template.Must(template.New("escape").Parse(templ))
	var data struct {
		A string        // untrusted plain text, will be escaped 
		B template.HTML // trusted HTML, preseve the markup
	}
    fmt.Printf("%T\n",data)
    data.A = "<b>Hello!</b>"
    data.B ="<b>Hello!</b>"
    //var  b template.HTML= template.HTML("test")
	if err := t.Execute(os.Stdout, data); err != nil {
		log.Fatal(err)
	}
}


struct { A string; B template.HTML }
<p>A: &lt;b&gt;Hello!&lt;/b&gt;</p><p>B: <b>Hello!</b></p>

[autoescape.html](http://skhuang.github.io/ch4/autoescape.html)

* for more information: 
<code>
$ go doc text/template
$ go doc html/template
</code>

In [ ]:
!go doc text/template

In [9]:
!go doc html/template

package template // import "html/template"

Package template (html/template) implements data-driven templates for generating
HTML output safe against code injection. It provides the same interface as
text/template and should be used instead of text/template whenever the output is
HTML.

The documentation here focuses on the security features of the package. For
information about how to program the templates themselves, see the documentation
for text/template.

# Introduction

This package wraps text/template so you can share its template API to parse and
execute HTML templates safely.

    tmpl, err := template.New("name").Parse(...)
    // Error checking elided
    err = tmpl.Execute(out, data)

If successful, tmpl will now be injection-safe. Otherwise, err is an error
defined in the docs for ErrorCode.

HTML templates treat data values as plain text which should be encoded so
they can be safely embedded in an HTML document. The escaping is contextual,
so actions can appear within Jav