<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#4.-Composite-Types-(II)" data-toc-modified-id="4.-Composite-Types-(II)-1">4. Composite Types (II)</a></span><ul class="toc-item"><li><span><a href="#4.1-Arrays" data-toc-modified-id="4.1-Arrays-1.1">4.1 Arrays</a></span></li><li><span><a href="#4.2-Slices" data-toc-modified-id="4.2-Slices-1.2">4.2 Slices</a></span></li><li><span><a href="#4.3-Maps" data-toc-modified-id="4.3-Maps-1.3">4.3 Maps</a></span></li><li><span><a href="#4.4-Structs" data-toc-modified-id="4.4-Structs-1.4">4.4 Structs</a></span><ul class="toc-item"><li><span><a href="#Recursive-Data-Structures" data-toc-modified-id="Recursive-Data-Structures-1.4.1">Recursive Data Structures</a></span></li><li><span><a href="#Struct-Literals" data-toc-modified-id="Struct-Literals-1.4.2">Struct Literals</a></span></li><li><span><a href="#Comparing-Structs" data-toc-modified-id="Comparing-Structs-1.4.3">Comparing Structs</a></span></li><li><span><a href="#Struct-Embedding-and-Anonymous-Fields" data-toc-modified-id="Struct-Embedding-and-Anonymous-Fields-1.4.4">Struct Embedding and Anonymous Fields</a></span></li></ul></li><li><span><a href="#4.5-JSON" data-toc-modified-id="4.5-JSON-1.5">4.5 JSON</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#github-HTTP-request" data-toc-modified-id="github-HTTP-request-1.5.0.1">github HTTP request</a></span></li><li><span><a href="#github-api-for-issues" data-toc-modified-id="github-api-for-issues-1.5.0.2">github api for issues</a></span></li></ul></li></ul></li><li><span><a href="#4.6-Text-and-HTML-Templates" data-toc-modified-id="4.6-Text-and-HTML-Templates-1.6">4.6 Text and HTML Templates</a></span></li></ul></li></ul></div>

# 4. Composite Types (II)
*    **Structs**
     *    Struct Literals
     *    Comparing Structs
     *    Struct Embedding and Anonymous Fields
*    JSON
*    Text and HTML Templates

## 4.1 Arrays
## 4.2 Slices 
## 4.3 Maps


## 4.4 Structs

* A struct is an aggregate data type grouping together zero or more named values of arbitrary types as a single entity
* Each value is called a field
* The name of a struct field is exported if it begins with a capital letter; this is Go's main access control mechanism
* A struct type may contain a mixture of exported and unexported fields

In [59]:
//Employee
import "fmt"
import "time"
type Employee struct {
    ID int
    Name string
    Address string
    DoB time.Time
    Position string
    Salary int
    ManagerID int
}
employeeDB := make(map[int]*Employee)
alan := Employee{ID:1, ManagerID: 3, Position: "Vice President"}
dilbert := Employee{ID:2, ManagerID: 1}
employeeDB[alan.ID] = &alan
employeeDB[dilbert.ID] = &dilbert
dilbert.Salary -= 5000
position := &dilbert.Position
*position = "Senior" + *position
var employeeOfTheMonth *Employee = &dilbert
employeeOfTheMonth.Position += " (proactive team player)"
//(*employeeOfTheMonth).Position += " (proactive team player)"
fmt.Printf("%q\n",employeeDB)
for _,emp := range employeeDB {
    fmt.Printf("%q\n",emp)
}

map['\x01':%!q(*struct { ID int; Name string; Address string; DoB time.Time; Position string; Salary int; ManagerID int }=&{1   {0 0 <nil>} Vice President 0 3}) '\x02':%!q(*struct { ID int; Name string; Address string; DoB time.Time; Position string; Salary int; ManagerID int }=&{2   {0 0 <nil>} Senior (proactive team player) -5000 1})]
&{'\x01' "" "" "0001-01-01 00:00:00 +0000 UTC" "Vice President" '\x00' '\x03'}
&{'\x02' "" "" "0001-01-01 00:00:00 +0000 UTC" "Senior (proactive team player)" '�' '\x01'}


In [3]:
import "fmt"
func EmployeeByID(id int) *Employee { return employeeDB[id]}
fmt.Println(EmployeeByID(dilbert.ManagerID).Position)
id := dilbert.ID    
EmployeeByID(id).Salary = 0  //dilert is fired

Vice President


### Recursive Data Structures
* Struc type ***S*** can't declare a field of the same type ***S***
  * aggregate value cannot containt itself
* S may declare a field of the pointer type \****S***
  * create recursive data structure like lists and trees
* Implement an insertion sort in the following

In [88]:
//gopl.io/ch4/treesort
import ("math/rand";"sort";"fmt")  
type tree struct {
	value       int
	left, right *tree
}

// Sort sorts values in place.
func Sort(values []int) {
	var root *tree
	for _, v := range values {
		root = add(root, v)
	}
	appendValues(values[:0], root) // append in the slice, the first position
    //appendValues(values, root)     // append in the last position
    //appendValues(values[:], root)    // append in the last position
}

// appendValues appends the elements of t to values in order
// and returns the resulting slice.
func appendValues(values []int, t *tree) []int {
    //fmt.Println(values,"len",len(values),cap(values))
	if t != nil {
		values = appendValues(values, t.left)
		values = append(values, t.value)
		values = appendValues(values, t.right)
	}
	return values
}

func add(t *tree, value int) *tree {
	if t == nil {
		// Equivalent to return &tree{value: value}.
		t = new(tree)
		t.value = value
		return t
	}
	if value < t.value {
		t.left = add(t.left, value)
	} else {
		t.right = add(t.right, value)
	}
	return t
}

data := make([]int, 50)
for i := range data {
	data[i] = rand.Int() % 50
}
    
	//treesort.Sort(data)
Sort(data)
//sort.Ints(data)
if !sort.IntsAreSorted(data) {
		fmt.Printf("not sorted: %v", data)
} else {
    fmt.Printf("sorted: %v", data)
}
//!-

sorted: [0 1 5 5 5 5 6 7 7 8 8 9 9 12 12 16 18 19 19 21 21 22 22 23 26 26 26 27 28 30 31 31 31 32 32 34 35 35 36 37 40 42 42 43 44 44 46 46 46 47]

<strike>$go get gopl.io/ch4</strike>
```
$go build gopl.io/ch4/treesort
$go install gopl.io/ch4/treesort
$go test gopl.io/ch4/treesort
```

### Struct Literals

* A value of a struct type can be written using a struct literal specifying values for its fields
* There are two forms of struct literal
* The first form requires a value be specified for every field, in the right order
* The second form is used, in which a struct value is initialized by listing some or all of the field names and their corresponding values
* The two forms cannot be mixed in the same literal

In [97]:
type Point struct{ X, Y int}
p := Point{1,2} // the first form
q := Point{X:1, Y:2} // the second form

In [105]:
package p
type T struct{ a, b int} // a and b are not exported
package q
import "p"
var _ = T{a:1, b:2} //compile error, can't reference a  and b 

### Comparing Structs
* If all the fields of a struct are comparable, the struct is comparable
* Two expressions of the comparable types may be compared using == or !!=

In [91]:
//comparing two points
type point struct{X, Y int}
p := Point{1,2}
q := Point{2,1}
fmt.Println(p.X == q.X && p.Y == q.Y)
fmt.Println(p == q)

false
false


6 <nil>

* Comparable struct types, may be used as the key type of a map

In [92]:
//comparable struct types as map key
type address struct {
    hostname string
    port     int
}
hits := make(map[address]int)
hits[address{"golang.org",443}]++
hits[address{"gopl.io",80}]+= 23
fmt.Println(hits)

map[{golang.org 443}:1 {gopl.io 80}:23]


40 <nil>

### Struct Embedding and Anonymous Fields

In [2]:
type Circle struct {
    X,Y, Radius int
}
type Wheel struct {
    X,Y, Radius, Spokes int
}
var w Wheel
w.X = 8
w.Y = 8
w.Radius = 5
w.Spokes = 20

* Factor out their common parts

In [93]:
import "fmt"
type Point struct {
    X, Y int
}
type Circle struct {
    Center Point
    Radius int
}
type Wheel struct {
    Circle Circle
    Spokes int
}
var w Wheel
w.Circle.Center.X = 8
w.Circle.Center.Y = 8
w.Circle.Radius = 5
w.Spokes = 20
fmt.Println(w)

{{{8 8} 5} 20}


15 <nil>

* Declare a field with a type but no name
* Such fields are called anonymous fields
* Due to embedding, we can refer to the names at the leaves of the implicit tree without giving the intervening names

In [94]:
//access the anonymous field
type Circle struct {
    Point
    Radius int
}
type Wheel struct {
    Circle 
    Spokes int
}
var w Wheel
w.X = 8    //w.Circle.Point.X
w.Y = 8    //w.Circle.Point.Y
w.Radius = 5 //w.Circle.Radius
w.Spokes = 20 
fmt.Println(w)

{{{8 8} 5} 20}


15 <nil>

* There's no corresponding shorthand for the struct literal syntax

In [9]:
w = Wheel{8,8,5,20} 

ERROR: cannot convert untyped constant {int 8} to <main.Circle>

In [24]:
w = Wheel{X:8, Y:8, Radius: 5, Spokes: 20}

ERROR: repl.go:1:5: unknown field 'X' in struct literal of type main.Wheel

In [110]:
//Anonymous Fields
type Point struct {
    X, Y int
}
type Circle struct {
    Point
    Radius int
}
type Wheel struct {
    Circle 
    Spokes int
}
var w Wheel
w = Wheel{Circle{Point{8, 8}, 5}, 20}

w = Wheel{
		Circle: Circle{
			Point:  Point{X: 8, Y: 8},
			Radius: 5,
		},
		Spokes: 20, // NOTE: trailing comma necessary here (and at Radius)
}

//fmt.Printf("%#v\n", w)
//%v	the value in a default format
//	when printing structs, the plus flag (%+v) adds field names
//%#v	a Go-syntax representation of the value
fmt.Printf("%+v\n",w)
	// Output:
	// Wheel{Circle:Circle{Point:Point{X:8, Y:8}, Radius:5}, Spokes:20}

w.X = 42

fmt.Printf("%#v\n", w)
fmt.Printf("%+v\n", w)
	// Output:
	// Wheel{Circle:Circle{Point:Point{X:42, Y:8}, Radius:5}, Spokes:20}
	//!-

{Circle:{Point:{X:8 Y:8} Radius:5} Spokes:20}
struct { Circle struct { Point struct { X int; Y int }; Radius int }; Spokes int }{Circle:struct { Point struct { X int; Y int }; Radius int }{Point:struct { X int; Y int }{X:42, Y:8}, Radius:5}, Spokes:20}
{Circle:{Point:{X:42 Y:8} Radius:5} Spokes:20}


47 <nil>

## 4.5 JSON
* JavaScript Object Notation (JSON) is a standard notation for sending and receiving structured information
* Other similar notation: XML, ASN.1, and Google's Protocol Buffers
* API: encoding/json, encoding/xml, encoding/asn1
* basic JSON types are numbers(decimal or scientific notation), booleans(true, false), and strings (sequene of Unicode code points)
* basic JSON types can be combined recursively using JSON arrays and objects
* JSON array is an ordered sequence of values, written as a comma-separated list enclosed in square brackets
* JSON array are used to encode Go arrays and slices
* JSON object is a mapping from strings to values, written as a sequence of name:value pairs separated by commas and surrounded by braces
* JSON objects are used to encode GO maps and structs

Example

type   |value
-------|-----------------------------------
boolean|true
number | -273.15
string |"She said \"Hello, 世界\""
array  | ["gold", "silver", "bronze"]
object |{"year": 1980,<br>"event": "archery",<br>"medals":["gold","silver","brone"]} 

* Gather movie reviews and offer recommendations
* String literals after the Year and Color field are field tags

In [112]:
//gopl.pl/ch4/movie
import ("encoding/json";"fmt";"log")

type Movie struct {
	Title  string
	Year   int  `json:"released"`
	Color  bool `json:"color,omitempty"`
	Actors []string
}

var movies = []Movie{
	{Title: "Casablanca", Year: 1942, Color: false,
		Actors: []string{"Humphrey Bogart", "Ingrid Bergman"}},
	{Title: "Cool Hand Luke", Year: 1967, Color: true,
		Actors: []string{"Paul Newman"}},
	{Title: "Bullitt", Year: 1968, Color: true,
		Actors: []string{"Steve McQueen", "Jacqueline Bisset"}},
	// ...
}

In [117]:
{		//!+Marshal
		data, err := json.Marshal(movies)
		if err != nil {
			log.Fatalf("JSON marshaling failed: %s", err)
		}
		fmt.Printf("%s\n", data)
}		//!-Marshal

[{"Title":"Casablanca","released":1942,"Actors":["Humphrey Bogart","Ingrid Bergman"]},{"Title":"Cool Hand Luke","released":1967,"color":true,"Actors":["Paul Newman"]},{"Title":"Bullitt","released":1968,"color":true,"Actors":["Steve McQueen","Jacqueline Bisset"]}]


* json.MarshalIndent produces neatly indented output
* two arguments: 
  * a prefix for each line of output 
  * a string for each level of indentation

In [118]:
//MarshalIndent	
{
		//!+MarshalIndent
		data, err := json.MarshalIndent(movies, "", "    ")
		if err != nil {
			log.Fatalf("JSON marshaling failed: %s", err)
		}
		fmt.Printf("%s\n", data)
		//!-MarshalIndent

		//!+Unmarshal
		var titles []struct{ Title string 
                            Year   int  `json:"released"`
                            Color  bool `json:"color,omitempty"`
                             Actors []string
                           }
		if err := json.Unmarshal(data, &titles); err != nil {
			log.Fatalf("JSON unmarshaling failed: %s", err)
		}
		fmt.Println(titles) // "[{Casablanca} {Cool Hand Luke} {Bullitt}]"
		//!-Unmarshal
	}

[
    {
        "Title": "Casablanca",
        "released": 1942,
        "Actors": [
            "Humphrey Bogart",
            "Ingrid Bergman"
        ]
    },
    {
        "Title": "Cool Hand Luke",
        "released": 1967,
        "color": true,
        "Actors": [
            "Paul Newman"
        ]
    },
    {
        "Title": "Bullitt",
        "released": 1968,
        "color": true,
        "Actors": [
            "Steve McQueen",
            "Jacqueline Bisset"
        ]
    }
]
[{Casablanca 1942 false [Humphrey Bogart Ingrid Bergman]} {Cool Hand Luke 1967 true [Paul Newman]} {Bullitt 1968 true [Steve McQueen Jacqueline Bisset]}]


#### github HTTP request 
* decode the result as JSON
* url.QueryEscape to escape \? and \&

In [14]:
//gopl.io/ch4/github
import "time"

const IssuesURL = "https://api.github.com/search/issues"

type IssuesSearchResult struct {
	TotalCount int `json:"total_count"`
	Items      []*Issue
}

type Issue struct {
	Number    int
	HTMLURL   string `json:"html_url"`
	Title     string
	State     string
	User      *User
	CreatedAt time.Time `json:"created_at"`
	Body      string    // in Markdown format
}

type User struct {
	Login   string
	HTMLURL string `json:"html_url"`
}

//!-

#### github api for issues
* [github issue api](https://api.github.com/search/issues?q=repo:golang/go%20is:open%20json%20decoder)
* struct fields are capitalized for public access even if JSON names are not
* matching process with JSON names and Go struct names is case-insensitive

In [2]:
import ("encoding/json";"fmt";"net/http";"net/url";"strings")

// SearchIssues queries the GitHub issue tracker.
func SearchIssues(terms []string) (*IssuesSearchResult, error) {
	q := url.QueryEscape(strings.Join(terms, " "))
	resp, err := http.Get(IssuesURL + "?q=" + q)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != http.StatusOK {
		resp.Body.Close()
		return nil, fmt.Errorf("search query failed: %s", resp.Status)
	}
    //fmt.Println(resp.Body)
    fmt.Printf("%q",resp.Body)
	var result IssuesSearchResult
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		resp.Body.Close()
		return nil, err
	}
	resp.Body.Close()
	return &result, nil
}

In [22]:
import ("fmt";"log";"os";"gopl.io/ch4/github")

func main() {
	//result, err := github.SearchIssues(os.Args[1:])
    t := []string{"repo:golang/go","is:open","json","decoder"}
    result, err := github.SearchIssues(t)
    //result, err := SearchIssues(t) 
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%d issues:\n", result.TotalCount)
	for _, item := range result.Items {
		fmt.Printf("#%-5d %9.9s %.55s\n",
			item.Number, item.User.Login, item.Title)
	}
}

ERROR: repl.go:6:20: undefined "github" in github.SearchIssues <*ast.SelectorExpr>

In [167]:
os.Args = []string{"./issues", "repo:golang/go", "is:open", "json", "decoder"}
main()

&{[] {%!q(*http.http2clientStream=&{0x14000269e00 {{}} <nil> <nil> 1 {{0 0} {{} <nil> {0 0 0 <nil> <nil>} 0} 0x14000aecc80 0 <nil> <nil> <nil> <nil>} true false {0 {0 0}} 0x140001009c0 <nil> 0x14000100960 0x14000100b40 <nil> 0x14000100ae0 0x14000b386c0 {[] 67108864 0x14000269e68} {4194304 0} -1 <nil> <nil> 0 <nil> true true true true false 0 false false map[] 0x14000b38738})} %!q(*gzip.Reader=<nil>) <nil>}85 issues:
#48298     dsnet encoding/json: add Decoder.DisallowDuplicateFields
#11046     kurin encoding/json: Decoder internally buffers full input
#36225     dsnet encoding/json: the Decoder.Decode API lends itself to m
#56733 rolandsho encoding/json: add (*Decoder).SetLimit
#61627    nabice x/tools/gopls: The rename command line may accept ident
#40128  rogpeppe proposal: encoding/json: garbage-free reading of tokens
#29035    jaswdr proposal: encoding/json: add error var to compare  the 
#41144 alvaroale encoding/json: Unmarshaler breaks DisallowUnknownFields
#5901        rsc enco

## 4.6 Text and HTML Templates
* the simplest formatting: Printf
* separate the format from the code 
* **text/template** and **html/template** packages provide a mechanism for substituting the values of variables into a text or HTML template 


* template is a string or file containing one or more portions enclosed in double braces, {{...}}, called actions
* Each action contains an expression in the template language
  * Printing values
  * Selecting struct fields
  * Calling functions and methods
  * Control flow such as if-else, range, and instantiating other templates

In [144]:
// template
import "fmt"
const templ = `{{.TotalCount}} issues:
{{range .Items}}----------------------------------------
Number: {{.Number}}
User:   {{.User.Login}}
Title:  {{.Title | printf "%.64s"}}
Age:    {{.CreatedAt | daysAgo}} days
{{end}}`
fmt.Println(templ)

{{.TotalCount}} issues:
{{range .Items}}----------------------------------------
Number: {{.Number}}
User:   {{.User.Login}}
Title:  {{.Title | printf "%.64s"}}
Age:    {{.CreatedAt | daysAgo}} days
{{end}}


207 <nil>

In [152]:
//Parse the template into a suitable internal represntation
import ("time";"text/template";"os")
func daysAgo(t time.Time) int {
    return int(time.Since(t).Hours()/24)
}
report, err := template.New("report").
   Funcs(template.FuncMap{"daysAgo": daysAgo}).
   Parse(templ)
if (err != nil) {
    fmt.Fprintln(os.Stderr,"error")
} else {
    fmt.Printf("%q\n",report)
}

&{"report" %!q(*parse.Tree=&{report report 0x14000a410b0 0 {{.TotalCount}} issues:
{{range .Items}}----------------------------------------
Number: {{.Number}}
User:   {{.User.Login}}
Title:  {{.Title | printf "%.64s"}}
Age:    {{.CreatedAt | daysAgo}} days
{{end}} [] <nil> [{8 206  7} {11 24 {{ 2} {0 0  0}] 1 [] map[] 0 0}) %!q(*template.common=&{map[report:0x14000666b00] {{0 0} 0 0 {{} 0} {{} 0}} {0} {{0 0} 0 0 {{} 0} {{} 0}} map[daysAgo:0x1000dd370] map[daysAgo:{0x100e8f4e0 0x14000a40ed0 19}]}) "" ""}


In [153]:
// Template fixed at compile time and template.Must handle the error condition
import ("log";"os";"text/template";"time";"gopl.io/ch4/github")
const templ = `{{.TotalCount}} issues:
{{range .Items}}----------------------------------------
Number: {{.Number}}
User:   {{.User.Login}}
Title:  {{.Title | printf "%.64s"}}
Age:    {{.CreatedAt | daysAgo}} days
{{end}}`

func daysAgo(t time.Time) int {
	return int(time.Since(t).Hours() / 24)
}

var report = template.Must(template.New("issuelist").
	Funcs(template.FuncMap{"daysAgo": daysAgo}).
	Parse(templ))

func main() {
	//result, err := github.SearchIssues(os.Args[1:])
    result, err := SearchIssues(os.Args[1:])
	if err != nil {
		log.Fatal(err)
	}
    fmt.Printf("%v\n",result)
	if err := report.Execute(os.Stdout, result); err != nil {
		log.Fatal(err)
	}
}



In [157]:
// not handle error, if parse error, exceptions occur
func noMust() {
	//!+parse
	report, err := template.New("report").
		Funcs(template.FuncMap{"daysAgo": daysAgo}).
		Parse(templ)
	if err != nil {
		log.Fatal(err)
	}
	//!-parse
	//result, err := github.SearchIssues(os.Args[1:])
    result, err := SearchIssues(os.Args[1:])
	if err != nil {
		log.Fatal(err)
	}
	if err := report.Execute(os.Stdout, result); err != nil {
		log.Fatal(err)
	}
}

In [158]:
os.Args = []string{"issuereport", "repo:golang/go","is:open","json","decoder"}
main()

&{[] {0x140007f4180} <nil> <nil>}
&{85 [0x14000fa07e0 0x14000fa08c0 0x14000fa0930 0x14000fa09a0 0x14000fa0a10 0x14000fa0a80 0x14000fa0af0 0x14000fa0b60 0x14000fa0bd0 0x14000fa0c40 0x14000fa0cb0 0x14000fa0d20 0x14000fa0d90 0x14000fa0e00 0x14000fa0e70 0x14000fa0ee0 0x14000fa0f50 0x14000fa0fc0 0x14000fa1030 0x14000fa1e30 0x14000fa1ea0 0x14000fa1f10 0x14000fa1f80 0x14000c99570 0x14000c99810 0x14000c99880 0x14000c998f0 0x14000c99960 0x14000c999d0 0x14000c99a40]}
85 issues:
----------------------------------------
Number: 48298
User:   dsnet
Title:  encoding/json: add Decoder.DisallowDuplicateFields
Age:    759 days
----------------------------------------
Number: 11046
User:   kurin
Title:  encoding/json: Decoder internally buffers full input
Age:    3049 days
----------------------------------------
Number: 36225
User:   dsnet
Title:  encoding/json: the Decoder.Decode API lends itself to misuse
Age:    1389 days
----------------------------------------
Number: 56733
User:   rolandshoemaker

In [159]:
noMust()  

&{[] {0x140007f5980} <nil> <nil>}
85 issues:
----------------------------------------
Number: 48298
User:   dsnet
Title:  encoding/json: add Decoder.DisallowDuplicateFields
Age:    759 days
----------------------------------------
Number: 11046
User:   kurin
Title:  encoding/json: Decoder internally buffers full input
Age:    3049 days
----------------------------------------
Number: 36225
User:   dsnet
Title:  encoding/json: the Decoder.Decode API lends itself to misuse
Age:    1389 days
----------------------------------------
Number: 56733
User:   rolandshoemaker
Title:  encoding/json: add (*Decoder).SetLimit
Age:    328 days
----------------------------------------
Number: 61627
User:   nabice
Title:  x/tools/gopls: The rename command line may accept identifiers in
Age:    73 days
----------------------------------------
Number: 40128
User:   rogpeppe
Title:  proposal: encoding/json: garbage-free reading of tokens
Age:    1187 days
----------------------------------------
Number: 2

* html/template use the same API and expression language as text/template
* with HTML, JavaScript, CSS, or URLs

In [160]:
//gopl.io/ch4/issueshtml
import ("log";"os";"gopl.io/ch4/github";"html/template")
var issueList = template.Must(template.New("issuelist").Parse(`
<h1>{{.TotalCount}} issues</h1>
<table border=1>
<tr style='text-align: left'>
  <th>#</th>
  <th>State</th>
  <th>User</th>
  <th>Title</th>
</tr>
{{range .Items}}
<tr>
  <td><a href='{{.HTMLURL}}'>{{.Number}}</a></td>
  <td>{{.State}}</td>
  <td><a href='{{.User.HTMLURL}}'>{{.User.Login}}</a></td>
  <td><a href='{{.HTMLURL}}'>{{.Title}}</a></td>
</tr>
{{end}}
</table>
`))

In [161]:
func main() {
	result, err := SearchIssues(os.Args[1:])
    //result, err := github.SearchIssues(os.Args[1:])
	if err != nil {
		log.Fatal(err)
	}
	if err := issueList.Execute(os.Stdout, result); err != nil {
		log.Fatal(err)
	}
}

In [162]:
os.Args = []string{"issuehtml","repo:golang/go","commenter:gopherbot","json","encoder"}
main()

&{[] {0x14000d2a600} <nil> <nil>}

<h1>83 issues</h1>
<table border=1>
<tr style='text-align: left'>
  <th>#</th>
  <th>State</th>
  <th>User</th>
  <th>Title</th>
</tr>

<tr>
  <td><a href='https://github.com/golang/go/issues/7872'>7872</a></td>
  <td>open</td>
  <td><a href='https://github.com/extemporalgenome'>extemporalgenome</a></td>
  <td><a href='https://github.com/golang/go/issues/7872'>encoding/json: Encoder internally buffers full output</a></td>
</tr>

<tr>
  <td><a href='https://github.com/golang/go/issues/40127'>40127</a></td>
  <td>open</td>
  <td><a href='https://github.com/rogpeppe'>rogpeppe</a></td>
  <td><a href='https://github.com/golang/go/issues/40127'>encoding/json: add Encoder.EncodeToken method</a></td>
</tr>

<tr>
  <td><a href='https://github.com/golang/go/issues/5901'>5901</a></td>
  <td>open</td>
  <td><a href='https://github.com/rsc'>rsc</a></td>
  <td><a href='https://github.com/golang/go/issues/5901'>encoding/json: allow per-Encoder/per-Decoder registrati

* [issues.html](http://skhuang.github.io/ch4/issues.html)
<code>
$ go build gopl.io/ch4/issueshtml
$ ./issueshtml repo:golang/go commenter:gopherbot json encoder >issues.html
</code>

In [43]:
os.Args = []string{"issuehtml","repo:golang/go","3133","10535"}
main()


<h1>2 issues</h1>
<table border=1>
<tr style='text-align: left'>
  <th>#</th>
  <th>State</th>
  <th>User</th>
  <th>Title</th>
</tr>

<tr>
  <td><a href='https://github.com/golang/go/issues/10535'>10535</a></td>
  <td>open</td>
  <td><a href='https://github.com/dvyukov'>dvyukov</a></td>
  <td><a href='https://github.com/golang/go/issues/10535'>x/net/html: void element &lt;link&gt; has child nodes</a></td>
</tr>

<tr>
  <td><a href='https://github.com/golang/go/issues/3133'>3133</a></td>
  <td>closed</td>
  <td><a href='https://github.com/ukai'>ukai</a></td>
  <td><a href='https://github.com/golang/go/issues/3133'>html/template: escape xmldesc as &amp;lt;?xml</a></td>
</tr>

</table>


[issues2.html](https://skhuang.github.io/ch4/issues2.html)
<code>
$ ./issueshtml repo:golang/go 3133 10535 >issues2.html
</code>

In [40]:
//gopl.io/ch4/autoescape
import ("fmt";"html/template";"log";"os")

//!+
func main() {
	const templ = `<p>A: {{.A}}</p><p>B: {{.B}}</p>`
	t := template.Must(template.New("escape").Parse(templ))
	var data struct {
		A string        // untrusted plain text, will be escaped 
		B template.HTML // trusted HTML, preseve the markup
	}
    fmt.Printf("%T\n",data)
    data.A = "<b>Hello!</b>"
    data.B ="<b>Hello!</b>"
    var  b template.HTML= template.HTML("test")
	if err := t.Execute(os.Stdout, data); err != nil {
		log.Fatal(err)
	}
}


ERROR: repl.go:14:5: error compiling assignment: data.B = "<b>Hello!</b>"
	reflect.Value.Convert: value of type reflect.Value cannot be converted to type template.HTML

[autoescape.html](http://skhuang.github.io/ch4/autoescape.html)

* for more information: 
<code>
$ go doc text/template
$ go doc html/template
</code>