<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Testing" data-toc-modified-id="Testing-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Testing</a></span><ul class="toc-item"><li><span><a href="#The-go-test-Tool" data-toc-modified-id="The-go-test-Tool-11.1"><span class="toc-item-num">11.1&nbsp;&nbsp;</span>The go test Tool</a></span></li><li><span><a href="#Test-Functions" data-toc-modified-id="Test-Functions-11.2"><span class="toc-item-num">11.2&nbsp;&nbsp;</span>Test Functions</a></span><ul class="toc-item"><li><span><a href="#More-Testing" data-toc-modified-id="More-Testing-11.2.1"><span class="toc-item-num">11.2.1&nbsp;&nbsp;</span>More Testing</a></span><ul class="toc-item"><li><span><a href="#Rewrite-the-functions" data-toc-modified-id="Rewrite-the-functions-11.2.1.1"><span class="toc-item-num">11.2.1.1&nbsp;&nbsp;</span>Rewrite the functions</a></span></li></ul></li><li><span><a href="#Table-driven-testing" data-toc-modified-id="Table-driven-testing-11.2.2"><span class="toc-item-num">11.2.2&nbsp;&nbsp;</span>Table-driven testing</a></span></li><li><span><a href="#Randomized-Testing" data-toc-modified-id="Randomized-Testing-11.2.3"><span class="toc-item-num">11.2.3&nbsp;&nbsp;</span>Randomized Testing</a></span></li><li><span><a href="#Testing-a-Command" data-toc-modified-id="Testing-a-Command-11.2.4"><span class="toc-item-num">11.2.4&nbsp;&nbsp;</span>Testing a Command</a></span></li><li><span><a href="#White-Box-Testing" data-toc-modified-id="White-Box-Testing-11.2.5"><span class="toc-item-num">11.2.5&nbsp;&nbsp;</span>White-Box Testing</a></span></li><li><span><a href="#Gomock" data-toc-modified-id="Gomock-11.2.6"><span class="toc-item-num">11.2.6&nbsp;&nbsp;</span>Gomock</a></span></li></ul></li><li><span><a href="#Coverage" data-toc-modified-id="Coverage-11.3"><span class="toc-item-num">11.3&nbsp;&nbsp;</span>Coverage</a></span></li><li><span><a href="#Benchmark-Functions" data-toc-modified-id="Benchmark-Functions-11.4"><span class="toc-item-num">11.4&nbsp;&nbsp;</span>Benchmark Functions</a></span></li><li><span><a href="#Profiling" data-toc-modified-id="Profiling-11.5"><span class="toc-item-num">11.5&nbsp;&nbsp;</span>Profiling</a></span></li><li><span><a href="#Example-Functions" data-toc-modified-id="Example-Functions-11.6"><span class="toc-item-num">11.6&nbsp;&nbsp;</span>Example Functions</a></span></li><li><span><a href="#Fuzz-Testing" data-toc-modified-id="Fuzz-Testing-11.7"><span class="toc-item-num">11.7&nbsp;&nbsp;</span>Fuzz Testing</a></span><ul class="toc-item"><li><span><a href="#Fix-the-double-reverse-error" data-toc-modified-id="Fix-the-double-reverse-error-11.7.1"><span class="toc-item-num">11.7.1&nbsp;&nbsp;</span>Fix the double reverse error</a></span></li><li><span><a href="#Fix-the-error" data-toc-modified-id="Fix-the-error-11.7.2"><span class="toc-item-num">11.7.2&nbsp;&nbsp;</span>Fix the error</a></span></li></ul></li></ul></li></ul></div>

# Testing

## The go test Tool

In [4]:
!go help test

usage: go test [build/test flags] [packages] [build/test flags & test binary flags]

'Go test' automates testing the packages named by the import paths.
It prints a summary of the test results in the format:

	ok   archive/tar   0.011s
	FAIL archive/zip   0.022s
	ok   compress/gzip 0.033s
	...

followed by detailed output for each failed package.

'Go test' recompiles each package along with any files with names matching
the file pattern "*_test.go".
These additional files can contain test functions, benchmark functions, fuzz
tests and example functions. See 'go help testfunc' for more.
Each listed package causes the execution of a separate test binary.
Files whose names begin with "_" (including "_test.go") or "." are ignored.

Test files that declare a package with the suffix "_test" will be compiled as a
separate package, and then linked and run with the main test binary.

The go tool will ignore a directory named "testdata", making it available
to hold ancillary data needed by the 

In [5]:
!go help testflag

The 'go test' command takes both flags that apply to 'go test' itself
and flags that apply to the resulting test binary.

Several of the flags control profiling and write an execution profile
suitable for "go tool pprof"; run "go tool pprof -h" for more
information. The --alloc_space, --alloc_objects, and --show_bytes
options of pprof control how the information is presented.

The following flags are recognized by the 'go test' command and
control the execution of any test:

	-bench regexp
	    Run only those benchmarks matching a regular expression.
	    By default, no benchmarks are run.
	    To run all benchmarks, use '-bench .' or '-bench=.'.
	    The regular expression is split by unbracketed slash (/)
	    characters into a sequence of regular expressions, and each
	    part of a benchmark's identifier must match the corresponding
	    element in the sequence, if any. Possible parents of matches
	    are run with b.N=1 to identify sub-benchmarks. For example,
	    given -bench=X/

[https://pkg.go.dev/testing](https://pkg.go.dev/testing)

## Test Functions

In [8]:
import "testing"
import "math"
func TestAbs(t *testing.T) {
    got := math.Abs(-1)
    if got != 1 {
        t.Errorf("Abs(-1) = %f; want 1", got)
    }
}
%test

=== RUN   TestAbs
--- PASS: TestAbs (0.00s)
PASS


In [9]:
//gopl.io/ch11/word1.go
//package word
func IsPalindrome(s string) bool {
  	for i := range s {
		if s[i] != s[len(s)-1-i] {
			return false
		}
	}
	return true
}


In [10]:
//gopl.io/ch11/word_test.go
//package word
import "testing"

func TestPalindrome(t *testing.T) {
    if !IsPalindrome("detartrated") {
       t.Error(`IsPalindrome('detartrated') = false`)
   }
}
func TestNonPalindrome(t *testing.T) {
   if IsPalindrome("palindrome") {
      t.Error(`IsPalindrome('palindrome') = false`) 
   }
}
%test

=== RUN   TestNonPalindrome
--- PASS: TestNonPalindrome (0.00s)
=== RUN   TestPalindrome
--- PASS: TestPalindrome (0.00s)
PASS


### More Testing

In [11]:
func TestFrenchPalindrome(t *testing.T) {
        if !IsPalindrome("été") {
                t.Error(`IsPalindrome("été") = false`)
        }
}

func TestCanalPalindrome(t *testing.T) {
        input := "A man, a plan, a canal: Panama"
        if !IsPalindrome(input) {
                t.Errorf(`IsPalindrome(%q) = false`, input)
        }
}
%test

=== RUN   TestCanalPalindrome
    main_test.go:64: IsPalindrome("A man, a plan, a canal: Panama") = false
--- FAIL: TestCanalPalindrome (0.00s)
=== RUN   TestFrenchPalindrome
    main_test.go:70: IsPalindrome("été") = false
--- FAIL: TestFrenchPalindrome (0.00s)
FAIL


exit status 1


In [41]:
//package word

import "testing"

func TestPalindrome(t *testing.T) {
        if !IsPalindrome("detartrated") {
                t.Error(`IsPalindrome("detartrated") = false`)
        }
        if !IsPalindrome("kayak") {
                t.Error(`IsPalindrome("kayak") = false`)
        }
}

func TestNonPalindrome(t *testing.T) {
        if IsPalindrome("palindrome") {
                t.Error(`IsPalindrome("palindrome") = true`)
        }
}
%test

=== RUN   TestNonPalindrome
--- PASS: TestNonPalindrome (0.00s)
=== RUN   TestPalindrome
--- PASS: TestPalindrome (0.00s)
PASS


In [12]:
import "unicode"
func IsPalindrome(s string) bool {
	var letters []rune
	for _, r := range s {
		if unicode.IsLetter(r) {
			letters = append(letters, unicode.ToLower(r))
		}
	}
	for i := range letters {
		if letters[i] != letters[len(letters)-1-i] {
			return false
		}
	}
	return true
}

<code>
$ go test -v gopl.io/ch11/word1
</code>

In [13]:
!go test -v gopl.io/ch11/word1

=== RUN   TestPalindrome
--- PASS: TestPalindrome (0.00s)
=== RUN   TestNonPalindrome
--- PASS: TestNonPalindrome (0.00s)
=== RUN   TestFrenchPalindrome
    word_test.go:32: IsPalindrome("été") = false
--- FAIL: TestFrenchPalindrome (0.00s)
=== RUN   TestCanalPalindrome
    word_test.go:39: IsPalindrome("A man, a plan, a canal: Panama") = false
--- FAIL: TestCanalPalindrome (0.00s)
FAIL
FAIL	gopl.io/ch11/word1	0.225s
FAIL


exit status 1


In [15]:
!go test -v -run="French|Canal" gopl.io/ch11/word1

=== RUN   TestFrenchPalindrome
    word_test.go:32: IsPalindrome("été") = false
--- FAIL: TestFrenchPalindrome (0.00s)
=== RUN   TestCanalPalindrome
    word_test.go:39: IsPalindrome("A man, a plan, a canal: Panama") = false
--- FAIL: TestCanalPalindrome (0.00s)
FAIL
FAIL	gopl.io/ch11/word1	0.224s
FAIL


exit status 1


#### Rewrite the functions

In [18]:
// IsPalindrome reports whether s reads the same forward and backward.
// Letter case is ignored, as are non-letters.
func IsPalindrome(s string) bool {
        //var letters []rune
        letters := make([]rune,0, len(s))
        for _, r := range s {
                if unicode.IsLetter(r) {
                        letters = append(letters, unicode.ToLower(r))
                }
        }
        //for i := range letters {
        n := len(letters)/2
        for i :=0; i<n; i++ {
                if letters[i] != letters[len(letters)-1-i] {
                        return false
                }
        }
        return true
}


In [19]:
func TestFrenchPalindrome(t *testing.T) {
        if !IsPalindrome("été") {
                t.Error(`IsPalindrome("été") = false`)
        }
}

func TestCanalPalindrome(t *testing.T) {
        input := "A man, a plan, a canal: Panama"
        if !IsPalindrome(input) {
                t.Errorf(`IsPalindrome(%q) = false`, input)
        }
}
%test

=== RUN   TestCanalPalindrome
--- PASS: TestCanalPalindrome (0.00s)
=== RUN   TestFrenchPalindrome
--- PASS: TestFrenchPalindrome (0.00s)
PASS


### Table-driven testing

In [22]:
import (
        "fmt"
        "math/rand"
        "time"
)

//!+bench

import "testing"

//!-bench

//!+test
func TestIsPalindrome(t *testing.T) {
        var tests = []struct {
                input string
                want  bool
        }{
                {"", true},
                {"a", true},
                {"aa", true},
                {"ab", false},
                {"kayak", true},
                   {"detartrated", true},
                {"A man, a plan, a canal: Panama", true},
                {"Evil I did dwell; lewd did I live.", true},
                {"Able was I ere I saw Elba", true},
                {"été", true},
                {"Et se resservir, ivresse reste.", true},
                {"palindrome", false}, // non-palindrome
                {"desserts", false},   // semi-palindrome
        }
        for _, test := range tests {
                if got := IsPalindrome(test.input); got != test.want {
                        t.Errorf("IsPalindrome(%q) = %v", test.input, got)
                }
        }
}
%test -test.v -test.run=Palindrome

=== RUN   TestCanalPalindrome
--- PASS: TestCanalPalindrome (0.00s)
=== RUN   TestFrenchPalindrome
--- PASS: TestFrenchPalindrome (0.00s)
=== RUN   TestIsPalindrome
--- PASS: TestIsPalindrome (0.00s)
=== RUN   TestNonPalindrome
--- PASS: TestNonPalindrome (0.00s)
=== RUN   TestPalindrome
--- PASS: TestPalindrome (0.00s)
PASS


### Randomized Testing

In [23]:
import "math/rand"
func randomPalindrome(rng *rand.Rand) string {
	n := rng.Intn(25) // random length up to 24
	runes := make([]rune, n)
	for i := 0; i < (n+1)/2; i++ {
		r := rune(rng.Intn(0x1000)) // random rune up to '\u0999'
		runes[i] = r
		runes[n-1-i] = r
	}
	return string(runes)
}

In [26]:
import "testing"
import "time"
func TestRandomPalindromes(t *testing.T) {
	// Initialize a pseudo-random number generator.
	seed := time.Now().UTC().UnixNano()
	t.Logf("Random seed: %d", seed)
	rng := rand.New(rand.NewSource(seed))

	for i := 0; i < 1000; i++ {
		p := randomPalindrome(rng)
		if !IsPalindrome(p) {
			t.Errorf("IsPalindrome(%q) = false", p)
		}
	}
}
%test -test.v -test.run="RandomPalindromes"

=== RUN   TestRandomPalindromes
    main_test.go:127: Random seed: 1733811026555066000
--- PASS: TestRandomPalindromes (0.00s)
PASS


In [27]:
!go test -v -run="Random" gopl.io/ch11/word2

=== RUN   TestRandomPalindromes
    word_test.go:92: Random seed: 1733728885003769000
--- PASS: TestRandomPalindromes (0.00s)
PASS
ok  	gopl.io/ch11/word2	(cached)


### Testing a Command

In [29]:
//gopl.io/ch11/echo
import (
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
)

var (
	n = flag.Bool("n", false, "omit trailing newline")
	s = flag.String("s", " ", "separator")
)
var out io.Writer = os.Stdout // modified during testing

func main() {
	flag.Parse()
	if err := echo(!*n, *s, flag.Args()); err != nil {
		fmt.Fprintf(os.Stderr, "echo: %v\n", err)
		os.Exit(1)
	}
}

func echo(newline bool, sep string, args []string) error {
	fmt.Fprint(out, strings.Join(args, sep))
	if newline {
		fmt.Fprintln(out)
	}
	return nil
}

In [31]:
// Test of echo command.  Run with: go test gopl.io/ch11/echo

//!+
//package main

import (
	"bytes"
	"fmt"
	"testing"
)

func TestEcho(t *testing.T) {
	var tests = []struct {
		newline bool
		sep     string
		args    []string
		want    string
	}{
		{true, "", []string{}, "\n"},
		{false, "", []string{}, ""},
		{true, "\t", []string{"one", "two", "three"}, "one\ttwo\tthree\n"},
		{true, ",", []string{"a", "b", "c"}, "a,b,c\n"},
		{false, ":", []string{"1", "2", "3"}, "1:2:3"},
	}

	for _, test := range tests {
		descr := fmt.Sprintf("echo(%v, %q, %q)",
			test.newline, test.sep, test.args)

		out = new(bytes.Buffer) // captured output
		if err := echo(test.newline, test.sep, test.args); err != nil {
			t.Errorf("%s failed: %v", descr, err)
			continue
		}
		got := out.(*bytes.Buffer).String()
		if got != test.want {
			t.Errorf("%s = %q, want %q", descr, got, test.want)
		}
	}
}
%test -test.v -test.run="Echo"

=== RUN   TestEcho
--- PASS: TestEcho (0.00s)
PASS


In [32]:
!go test -v gopl.io/ch11/echo

=== RUN   TestEcho
--- PASS: TestEcho (0.00s)
PASS
ok  	gopl.io/ch11/echo	(cached)


### White-Box Testing

In [33]:
//gopl.io/ch11/storage1
// Copyright © 2016 Alan A. A. Donovan & Brian W. Kernighan.
// License: https://creativecommons.org/licenses/by-nc-sa/4.0/

// See page 311.

// Package storage is part of a hypothetical cloud storage server.
//!+main
//package storage

import (
	"fmt"
	"log"
	"net/smtp"
)

var usage = make(map[string]int64)

func bytesInUse(username string) int64 { return usage[username] }

// Email sender configuration.
// NOTE: never put passwords in source code!
const sender = "notifications@example.com"
const password = "correcthorsebatterystaple"
const hostname = "smtp.example.com"

const template = `Warning: you are using %d bytes of storage, %d%% of your quota.`

func CheckQuota(username string) {
	used := bytesInUse(username)
	const quota = 1000000000 // 1GB
	percent := 100 * used / quota
	if percent < 90 {
		return // OK
	}
	msg := fmt.Sprintf(template, used, percent)
	auth := smtp.PlainAuth("", sender, password, hostname)
	err := smtp.SendMail(hostname+":587", auth, sender,
		[]string{username}, []byte(msg))
	if err != nil {
		log.Printf("smtp.SendMail(%s) failed: %s", username, err)
	}
}

//!-main

In [34]:
//gopl.io/ch11/storage2
// Copyright © 2016 Alan A. A. Donovan & Brian W. Kernighan.
// License: https://creativecommons.org/licenses/by-nc-sa/4.0/

// See page 312.

// Package storage is part of a hypothetical cloud storage server.
//package storage

import (
	"fmt"
	"log"
	"net/smtp"
)

var usage = make(map[string]int64)

func bytesInUse(username string) int64 { return usage[username] }

// E-mail sender configuration.
// NOTE: never put passwords in source code!
const sender = "notifications@example.com"
const password = "correcthorsebatterystaple"
const hostname = "smtp.example.com"

const template = `Warning: you are using %d bytes of storage, %d%% of your quota.`

//!+factored
var notifyUser = func(username, msg string) {
	auth := smtp.PlainAuth("", sender, password, hostname)
	err := smtp.SendMail(hostname+":587", auth, sender,
		[]string{username}, []byte(msg))
	if err != nil {
		log.Printf("smtp.SendMail(%s) failed: %s", username, err)
	}
}

func CheckQuota(username string) {
	used := bytesInUse(username)
	const quota = 1000000000 // 1GB
	percent := 100 * used / quota
	if percent < 90 {
		return // OK
	}
	msg := fmt.Sprintf(template, used, percent)
	notifyUser(username, msg)
}

//!-factored

In [35]:
//gopl.io/ch11/quota_test.go
// Copyright © 2016 Alan A. A. Donovan & Brian W. Kernighan.
// License: https://creativecommons.org/licenses/by-nc-sa/4.0/

//!+test
//package storage

import (
	"strings"
	"testing"
)

func TestCheckQuotaNotifiesUser(t *testing.T) {
	var notifiedUser, notifiedMsg string
	notifyUser = func(user, msg string) {
		notifiedUser, notifiedMsg = user, msg
	}

	const user = "joe@example.org"
	usage[user] = 980000000 // simulate a 980MB-used condition

	CheckQuota(user)
	if notifiedUser == "" && notifiedMsg == "" {
		t.Fatalf("notifyUser not called")
	}
	if notifiedUser != user {
		t.Errorf("wrong user (%s) notified, want %s",
			notifiedUser, user)
	}
	const wantSubstring = "98% of your quota"
	if !strings.Contains(notifiedMsg, wantSubstring) {
		t.Errorf("unexpected notification message <<%s>>, "+
			"want substring %q", notifiedMsg, wantSubstring)
	}
}

//!-test

/*
//!+defer
func TestCheckQuotaNotifiesUser(t *testing.T) {
	// Save and restore original notifyUser.
	saved := notifyUser
	defer func() { notifyUser = saved }()
	// Install the test's fake notifyUser.
	var notifiedUser, notifiedMsg string
	notifyUser = func(user, msg string) {
		notifiedUser, notifiedMsg = user, msg
	}
	// ...rest of test...
}
//!-defer
*/
%test

=== RUN   TestCheckQuotaNotifiesUser
--- PASS: TestCheckQuotaNotifiesUser (0.00s)
PASS


In [36]:
!go test -v gopl.io/ch11/storage2

=== RUN   TestCheckQuotaNotifiesUser
--- PASS: TestCheckQuotaNotifiesUser (0.00s)
PASS
ok  	gopl.io/ch11/storage2	(cached)


[go library source](https://go.dev/src/fmt/)

In [37]:
!go list -f={{.GoFiles}} fmt


[doc.go errors.go format.go print.go scan.go]


In [38]:
!go list -f={{.TestGoFiles}} fmt


[export_test.go]


In [39]:
!go list -f={{.XTestGoFiles}} fmt

[errors_test.go example_test.go fmt_test.go gostringer_example_test.go scan_test.go state_test.go stringer_example_test.go stringer_test.go]


### Gomock
* GoMock is a mocking framework for the Go programming language.
* It integrates well with Go’s built-in testing package, but can be used in other contexts too.
* installation
  * go install github.com/golang/mock/gomock
  * go install github.com/golang/mock/mockgen


In [40]:
type DB interface {
        Get(key string) (int, error)
}

func GetFromDB(db DB, key string) int {
        if value, err := db.Get(key); err == nil {
                return value
        }

        return -1
}


In [41]:
// mockgen -source=db.go -destination=db_mock.go -package=main
// Code generated by MockGen. DO NOT EDIT.
// Source: db.go

// Package main is a generated GoMock package.
//package main

import (
        reflect "reflect"

        gomock "github.com/golang/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
        ctrl     *gomock.Controller
        recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
        mock *MockDB
}
// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
        mock := &MockDB{ctrl: ctrl}
        mock.recorder = &MockDBMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
        return m.recorder
}

// Get mocks base method.
func (m *MockDB) Get(key string) (int, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Get", key)
        ret0, _ := ret[0].(int)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDBMockRecorder) Get(key interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDB)(nil).Get), key)
}

In [42]:
import (
        gomock "github.com/golang/mock/gomock"
        "testing"
        "errors"
)
func TestGetFromDB(t *testing.T) {
        ctrl := gomock.NewController(t)
        defer ctrl.Finish()

        m := NewMockDB(ctrl)
        m.EXPECT().Get(gomock.Eq("Tom")).Return(100, errors.New("not exist"))

        if v := GetFromDB(m, "Tom"); v != -1 {
                t.Fatal("expected -1, but got", v)
        }
}
%test -test.v -test.run="GetFromDB"

=== RUN   TestGetFromDB
--- PASS: TestGetFromDB (0.00s)
PASS


## Coverage

In [43]:
import ("fmt";"math";"testing")
import ("gopl.io/ch7/eval")
func TestEval(t *testing.T) {
        tests := []struct {
                expr string
                env  eval.Env
                want string
        }{
                {"sqrt(A / pi)", eval.Env{"A": 87616, "pi": math.Pi}, "167"},
                {"pow(x, 3) + pow(y, 3)", eval.Env{"x": 12, "y": 1}, "1729"},
                {"pow(x, 3) + pow(y, 3)", eval.Env{"x": 9, "y": 10}, "1729"},
                {"5 / 9 * (F - 32)", eval.Env{"F": -40}, "-40"},
                {"5 / 9 * (F - 32)", eval.Env{"F": 32}, "0"},
                {"5 / 9 * (F - 32)", eval.Env{"F": 212}, "100"},
                //!-Eval
                // additional tests that don't appear in the book
                {"-1 + -x", eval.Env{"x": 1}, "-2"},
                {"-1 - x", eval.Env{"x": 1}, "-2"},
                //!+Eval
        }
        var prevExpr string
        for _, test := range tests {
                // Print expr only when it changes.
                if test.expr != prevExpr {
                        fmt.Printf("\n%s\n", test.expr)
                        prevExpr = test.expr
                }
                expr, err := eval.Parse(test.expr)
                if err != nil {
                        t.Error(err) // parse error
                        continue
                }
                got := fmt.Sprintf("%.6g", expr.Eval(test.env))
                fmt.Printf("\t%v => %s\n", test.env, got)
                if got != test.want {
                        t.Errorf("%s.Eval() in %v = %q, want %q\n",
                                test.expr, test.env, got, test.want)
                }
        }
}
%test 

=== RUN   TestEval

sqrt(A / pi)
	map[A:87616 pi:3.141592653589793] => 167

pow(x, 3) + pow(y, 3)
	map[x:12 y:1] => 1729
	map[x:9 y:10] => 1729

5 / 9 * (F - 32)
	map[F:-40] => -40
	map[F:32] => 0
	map[F:212] => 100

-1 + -x
	map[x:1] => -2

-1 - x
	map[x:1] => -2
--- PASS: TestEval (0.00s)
PASS


<code>
$ go test -v -run=Coverage gopl.io/ch7/eval 
=== RUN   TestCoverage
--- PASS: TestCoverage (0.00s)
PASS
ok      gopl.io/ch7/eval    0.011s
</code>

In [44]:
!go test -v -run=Coverage gopl.io/ch7/eval 

=== RUN   TestCoverage
--- PASS: TestCoverage (0.00s)
PASS
ok  	gopl.io/ch7/eval	(cached)


<code>
$ go test -v -run=Coverage -coverprofile=c.out gopl.io/ch7/eval
=== RUN   TestCoverage
--- PASS: TestCoverage (0.00s)
PASS
coverage: 63.8% of statements
ok      gopl.io/ch7/eval        0.018s  coverage: 63.8% of statements
</code>

In [45]:
!go test -v -run=Coverage -coverprofile=c.out gopl.io/ch7/eval

=== RUN   TestCoverage
--- PASS: TestCoverage (0.00s)
PASS
coverage: 63.8% of statements
ok  	gopl.io/ch7/eval	0.277s	coverage: 63.8% of statements


<code>
$ go tool cover -html=c.out
HTML output written to /tmp/cover854632247/coverage.html
</code>

In [46]:
!go tool cover -html=c.out

[coverage.html](cover3574731311/coverage.html)

## Benchmark Functions

In [47]:
func BenchmarkIsPalindrome(b *testing.B) {
        for i := 0; i < b.N; i++ {
                IsPalindrome("A man, a plan, a canal: Panama")
        }
}

In [48]:
//word.go.1
func IsPalindrome(s string) bool {
        var letters []rune
        for _, r := range s {
                if unicode.IsLetter(r) {
                        letters = append(letters, unicode.ToLower(r))
                }
        }
        for i := range letters {
                if letters[i] != letters[len(letters)-1-i] {
                        return false
                }
        }
        return true
}

<code>
$ rm word.go; ln -s word.go.1 word.go; go test -bench=.
goos: linux
goarch: amd64
pkg: gopl.io/ch11/word2
cpu: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
BenchmarkIsPalindrome-4          3274288               376.9 ns/op
PASS
ok      gopl.io/ch11/word2      1.627s
</code>

In [49]:
!(pwd;cd word2;rm word.go; ln -s word.go.1 word.go; go test -bench=.)

/Users/skhuang/course/go2024/go2024/ch11
goos: darwin
goarch: arm64
pkg: ch7/ch11/word2
cpu: Apple M1 Pro
BenchmarkIsPalindrome-10    	 5866180	       208.3 ns/op
PASS
ok  	ch7/ch11/word2	1.670s


<code>
rm word.go; ln -s word.go.1 word.go; go test -bench=. -benchmem
goos: linux
goarch: amd64
pkg: gopl.io/ch11/word2
cpu: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
BenchmarkIsPalindrome-4          2169936               545.5 ns/op           248 B/op          5 allocs/op
PASS
ok      gopl.io/ch11/word2      1.773s
</code>

In [50]:
!(cd word2;rm word.go; ln -s word.go.1 word.go; go test -bench=. -benchmem)

goos: darwin
goarch: arm64
pkg: ch7/ch11/word2
cpu: Apple M1 Pro
BenchmarkIsPalindrome-10    	 7086422	       169.5 ns/op	     248 B/op	       5 allocs/op
PASS
ok  	ch7/ch11/word2	3.410s


-----------

In [51]:
//word.go.2
func IsPalindrome(s string) bool {
        var letters []rune
        for _, r := range s {
                if unicode.IsLetter(r) {
                        letters = append(letters, unicode.ToLower(r))
                }
        }
        //for i := range letters {
        n := len(letters)/2
        for i :=0; i<n; i++ {
                if letters[i] != letters[len(letters)-1-i] {
                        return false
                }
        }
        return true
}

<code>
$ rm word.go; ln -s word.go.2 word.go; go test -bench=.
goos: linux
goarch: amd64
pkg: gopl.io/ch11/word2
cpu: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
BenchmarkIsPalindrome-4          3230330               363.3 ns/op
PASS
ok      gopl.io/ch11/word2      1.571s
</code>

In [53]:
!(cd word2;rm word.go; ln -s word.go.2 word.go; go test -bench=.)

goos: darwin
goarch: arm64
pkg: ch7/ch11/word2
cpu: Apple M1 Pro
BenchmarkIsPalindrome-10    	 4505208	       223.2 ns/op
PASS
ok  	ch7/ch11/word2	1.422s


<code>
rm word.go; ln -s word.go.2 word.go; go test -bench=. -benchmem
goos: linux
goarch: amd64
pkg: gopl.io/ch11/word2
cpu: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
BenchmarkIsPalindrome-4          3204992               364.9 ns/op           248 B/op          5 allocs/op
PASS
ok      gopl.io/ch11/word2      1.574s
    </code>

In [54]:
!(cd word2;rm word.go; ln -s word.go.2 word.go; go test -bench=. -benchmem)

goos: darwin
goarch: arm64
pkg: ch7/ch11/word2
cpu: Apple M1 Pro
BenchmarkIsPalindrome-10    	 6166152	       197.0 ns/op	     248 B/op	       5 allocs/op
PASS
ok  	ch7/ch11/word2	1.651s


----

In [55]:
//word.go.3
func IsPalindrome(s string) bool {
        //var letters []rune
        letters := make([]rune,0, len(s))
        for _, r := range s {
                if unicode.IsLetter(r) {
                        letters = append(letters, unicode.ToLower(r))
                }
        }
        for i := range letters {
                if letters[i] != letters[len(letters)-1-i] {
                        return false
                }
        }
        return true
}

<code>
$ rm word.go; ln -s word.go.3 word.go; go test -bench=.
goos: linux
goarch: amd64
pkg: gopl.io/ch11/word2
cpu: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
BenchmarkIsPalindrome-4          5476538               209.7 ns/op
PASS
ok      gopl.io/ch11/word2      1.390s
</code>

In [56]:
!(cd word2;rm word.go; ln -s word.go.3 word.go; go test -bench=.)

goos: darwin
goarch: arm64
pkg: ch7/ch11/word2
cpu: Apple M1 Pro
BenchmarkIsPalindrome-10    	10172282	       110.6 ns/op
PASS
ok  	ch7/ch11/word2	1.479s


<code>
rm word.go; ln -s word.go.3 word.go; go test -bench=. -benchmem
goos: linux
goarch: amd64
pkg: gopl.io/ch11/word2
cpu: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
BenchmarkIsPalindrome-4          5408686               211.7 ns/op           128 B/op          1 allocs/op
PASS
ok      gopl.io/ch11/word2      1.390s
</code>

In [59]:
!(cd word2;rm word.go; ln -s word.go.3 word.go; go test -bench=. -benchmem)

goos: darwin
goarch: arm64
pkg: ch7/ch11/word2
cpu: Apple M1 Pro
BenchmarkIsPalindrome-10    	11202406	       110.7 ns/op	     128 B/op	       1 allocs/op
PASS
ok  	ch7/ch11/word2	1.558s


------

In [60]:
//word.go.4
func IsPalindrome(s string) bool {
        //var letters []rune
        letters := make([]rune,0, len(s))
        for _, r := range s {
                if unicode.IsLetter(r) {
                        letters = append(letters, unicode.ToLower(r))
                }
        }
        //for i := range letters {
        n := len(letters)/2
        for i :=0; i<n; i++ {
                if letters[i] != letters[len(letters)-1-i] {
                        return false
                }
        }
        return true
}

<code>
rm word.go; ln -s word.go.4 word.go; go test -bench=.
goos: linux
goarch: amd64
pkg: gopl.io/ch11/word2
cpu: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
BenchmarkIsPalindrome-4          5644834               191.5 ns/op
PASS
ok      gopl.io/ch11/word2      1.319s
</code>

In [62]:
!(cd word2;rm word.go; ln -s word.go.4 word.go; go test -bench=.)

goos: darwin
goarch: arm64
pkg: ch7/ch11/word2
cpu: Apple M1 Pro
BenchmarkIsPalindrome-10    	12174042	       107.3 ns/op
PASS
ok  	ch7/ch11/word2	1.632s


<code>
rm word.go; ln -s word.go.4 word.go; go test -bench=. -benchmem
goos: linux
goarch: amd64
pkg: gopl.io/ch11/word2
cpu: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
BenchmarkIsPalindrome-4          5759314               194.2 ns/op           128 B/op          1 allocs/op
PASS
ok      gopl.io/ch11/word2      1.354s
</code>

In [63]:
!(cd word2;rm word.go; ln -s word.go.4 word.go; go test -bench=. -benchmem)

goos: darwin
goarch: arm64
pkg: ch7/ch11/word2
cpu: Apple M1 Pro
BenchmarkIsPalindrome-10    	11736342	        98.88 ns/op	     128 B/op	       1 allocs/op
PASS
ok  	ch7/ch11/word2	1.485s


## Profiling

<code>
$ ulimit -n 4000
$ go test -run=NONE -bench=ClientServerParallelTLS64 -cpuprofile=cpu.log net/http
PASS
goos: linux
goarch: amd64
pkg: net/http
cpu: Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz
BenchmarkClientServerParallelTLS64-4    2021/12/21 16:37:16 http: TLS handshake error fr
om 127.0.0.1:42421: read tcp 127.0.0.1:36819->127.0.0.1:42421: use of closed network con
nection
2021/12/21 16:37:16 http: TLS handshake error from 127.0.0.1:42450: read tcp 127.0.0.1:3
6819->127.0.0.1:42450: use of closed network connection
2021/12/21 16:37:16 http: TLS handshake error from 127.0.0.1:42463: read tcp 127.0.0.1:3
6819->127.0.0.1:42463: use of closed network connection
2021/12/21 16:37:16 http: TLS handshake error from 127.0.0.1:42454: write tcp 127.0.0.1:
36819->127.0.0.1:42454: use of closed network connection
2021/12/21 16:37:16 http: TLS handshake error from 127.0.0.1:42481: read tcp 127.0.0.1:3
6819->127.0.0.1:42481: use of closed network connection
2021/12/21 16:37:16 http: TLS handshake error from 127.0.0.1:42483: read tcp 127.0.0.1:3
6819->127.0.0.1:42483: use of closed network connection
2021/12/21 16:37:16 http: TLS handshake error from 127.0.0.1:42456: write tcp 127.0.0.1:
36819->127.0.0.1:42456: use of closed network connection
2021/12/21 16:37:16 http: TLS handshake error from 127.0.0.1:42479: write tcp 127.0.0.1:
36819->127.0.0.1:42479: use of closed network connection
2021/12/21 16:37:16 http: TLS handshake error from 127.0.0.1:42471: write tcp 127.0.0.1:
36819->127.0.0.1:42471: use of closed network connection
</code>

In [14]:
//!(ulimit -n 4000;go test -run=NONE -bench=ClientServerParallelTLS64 -cpuprofile=cpu.log net/http)
!(ulimit -n 4000;go test -run=NONE -bench=ClientServerParallel -cpuprofile=cpu.log net/http)

goos: darwin
goarch: arm64
pkg: net/http
cpu: Apple M1 Pro
BenchmarkClientServerParallel/4/h1-10         	   42391	    244250 ns/op	    9181 B/op	      82 allocs/op
--- BENCH: BenchmarkClientServerParallel/4/h1-10
    serve_test.go:5177: Get: Get "http://127.0.0.1:51965": dial tcp 127.0.0.1:51965: connect: can't assign requested address
    serve_test.go:5177: Get: Get "http://127.0.0.1:51965": dial tcp 127.0.0.1:51965: connect: can't assign requested address
    serve_test.go:5177: Get: Get "http://127.0.0.1:51965": dial tcp 127.0.0.1:51965: connect: can't assign requested address
    serve_test.go:5177: Get: Get "http://127.0.0.1:51965": dial tcp 127.0.0.1:51965: connect: can't assign requested address
    serve_test.go:5177: Get: Get "http://127.0.0.1:51965": dial tcp 127.0.0.1:51965: connect: can't assign requested address
    serve_test.go:5177: Get: Get "http://127.0.0.1:51965": dial tcp 127.0.0.1:51965: connect: can't assign requested address
    serve_test.go:5177: Get: Get "ht

PASS
ok  	net/http	17.007s


<code>
go tool pprof -text -nodecount=10 ./http.test cpu.log
File: http.test
Type: cpu
Time: Dec 21, 2021 at 4:37pm (CST)
Duration: 3.95s, Total samples = 9300ms (235.73%)
Showing nodes accounting for 6210ms, 66.77% of 9300ms total
Dropped 355 nodes (cum <= 46.50ms)
Showing top 10 nodes out of 229
      flat  flat%   sum%        cum   cum%
    1840ms 19.78% 19.78%     1840ms 19.78%  math/big.addMulVVW
    1340ms 14.41% 34.19%     1340ms 14.41%  vendor/golang.org/x/crypto/curve25519.ladderstep
    1060ms 11.40% 45.59%     1080ms 11.61%  syscall.Syscall
     560ms  6.02% 51.61%     2400ms 25.81%  math/big.nat.montgomery
     550ms  5.91% 57.53%      550ms  5.91%  crypto/sha256.block
     220ms  2.37% 59.89%      440ms  4.73%  runtime.pcvalue
     180ms  1.94% 61.83%      210ms  2.26%  runtime.step
     160ms  1.72% 63.55%      160ms  1.72%  vendor/golang.org/x/crypto/curve25519.square
     150ms  1.61% 65.16%      170ms  1.83%  runtime.findObject
     150ms  1.61% 66.77%      850ms  9.14%  runtime.mallocgc
</code>

In [13]:
!go tool pprof -text -nodecount=10 ./http.test cpu.log

File: http.test
Type: cpu
Time: Dec 11, 2024 at 10:06am (CST)
Duration: 202.39ms, Total samples = 0 
Showing nodes accounting for 0, 0% of 0 total
      flat  flat%   sum%        cum   cum%


## Example Functions

In [69]:
func ExampleIsPalindrome() {
        fmt.Println(IsPalindrome("A man, a plan, a canal: Panama"))
        fmt.Println(IsPalindrome("palindrome"))
        // Output:
        // true
        // false
}


## Fuzz Testing

* An installation of Go 1.18 or later. 
* A tool to edit your code. Any text editor you have will work fine.
* A command terminal. Go works well using any terminal on Linux and Mac, and on PowerShell or cmd in Windows.
* An environment that supports fuzzing. 
  * Go fuzzing with coverage instrumentation is only available on AMD64 and ARM64 architectures currently.

In [1]:
func Reverse(s string) string {
    b := []byte(s)
    for i, j := 0, len(b)-1; i < len(b)/2; i, j = i+1, j-1 {
        b[i], b[j] = b[j], b[i]
    }
    return string(b)
}

In [2]:
func main() {
    input := "The quick brown fox jumped over the lazy dog"
    rev := Reverse(input)
    doubleRev := Reverse(rev)
    fmt.Printf("original: %q\n", input)
    fmt.Printf("reversed: %q\n", rev)
    fmt.Printf("reversed again: %q\n", doubleRev)
}

original: "The quick brown fox jumped over the lazy dog"
reversed: "god yzal eht revo depmuj xof nworb kciuq ehT"
reversed again: "The quick brown fox jumped over the lazy dog"


In [3]:
!pwd
!(cd fuzz;go run .)

/Users/skhuang/course/go2024/go2024/ch11
original: "The quick brown fox jumped over the lazy dog"
reversed: "god yzal eht revo depmuj xof nworb kciuq ehT", err: <nil>
reversed again: "The quick brown fox jumped over the lazy dog", err: <nil>


In [4]:
//reverse_test.go
import (
    "testing"
)

func TestReverse(t *testing.T) {
    testcases := []struct {
        in, want string
    }{
        {"Hello, world", "dlrow ,olleH"},
        {" ", " "},
        {"!12345", "54321!"},
    }
    for _, tc := range testcases {
        rev := Reverse(tc.in)
        if rev != tc.want {
                t.Errorf("Reverse: %q, want %q", rev, tc.want)
        }
    }
}
%test

=== RUN   TestReverse
--- PASS: TestReverse (0.00s)
PASS


In [5]:
!(cd fuzz; go test -run="TestReverse" -v)

=== RUN   TestReverse
--- PASS: TestReverse (0.00s)
PASS
ok  	example/fuzz	0.236s


In [7]:
//Add a fuzz test
func FuzzReverse(f *testing.F) {
    testcases := []string{"Hello, world", " ", "!12345"}
    for _, tc := range testcases {
        f.Add(tc)  // Use f.Add to provide a seed corpus
    }
    f.Fuzz(func(t *testing.T, orig string) {
        rev := Reverse(orig)
        doubleRev := Reverse(rev)
        if orig != doubleRev {
            t.Errorf("Before: %q, after: %q", orig, doubleRev)
        }
        if utf8.ValidString(orig) && !utf8.ValidString(rev) {
            t.Errorf("Reverse produced invalid UTF-8 string %q", rev)
        }
    })
}


In [8]:
!(cd fuzz; ./reset1; go test -fuzz="Fuzz" -v)

=== RUN   TestReverse
--- PASS: TestReverse (0.00s)
=== RUN   FuzzReverse
fuzz: elapsed: 0s, gathering baseline coverage: 0/50 completed
failure while testing seed corpus entry: FuzzReverse/2b80f300eed1881c
fuzz: elapsed: 0s, gathering baseline coverage: 4/50 completed
--- FAIL: FuzzReverse (0.04s)
    --- FAIL: FuzzReverse (0.00s)
        reverse_test.go:36: Reverse produced invalid UTF-8 string "\x90\x90\x98\U000d0418\U000d0418\U000d0418\xf3"
    
=== NAME  
FAIL
exit status 1
FAIL	example/fuzz	0.270s


exit status 1


In [9]:
!cat fuzz/testdata/fuzz/FuzzReverse/d5b6b60965e92e557798e88a10d04e5fb1070907a7dc6118b367e4fb501354bd

go test fuzz v1
string("Ա")


In [10]:
!(cd fuzz; go test)

--- FAIL: FuzzReverse (0.00s)
    --- FAIL: FuzzReverse/2b80f300eed1881c (0.00s)
        reverse_test.go:36: Reverse produced invalid UTF-8 string "\x90\x90\x98\U000d0418\U000d0418\U000d0418\xf3"
    --- FAIL: FuzzReverse/d5b6b60965e92e557798e88a10d04e5fb1070907a7dc6118b367e4fb501354bd (0.00s)
        reverse_test.go:36: Reverse produced invalid UTF-8 string "\xb1\xd4"
FAIL
exit status 1
FAIL	example/fuzz	0.233s


exit status 1


### Fix the double reverse error

In [11]:
func Reverse(s string) string {
    fmt.Printf("input: %q\n", s)
    //b := []byte(s)
    r := []rune(s)
    fmt.Printf("runes: %q\n", r)
    for i, j := 0, len(r)-1; i < len(r)/2; i, j = i+1, j-1 {
        r[i], r[j] = r[j], r[i]
    }
    return string(r)
}
func main() {
    input := "The quick brown fox jumped over the lazy dog"
    rev := Reverse(input)
    doubleRev := Reverse(rev)
    fmt.Printf("original: %q\n", input)
    fmt.Printf("reversed: %q\n", rev)
    fmt.Printf("reversed again: %q\n", doubleRev)
}


input: "The quick brown fox jumped over the lazy dog"
runes: ['T' 'h' 'e' ' ' 'q' 'u' 'i' 'c' 'k' ' ' 'b' 'r' 'o' 'w' 'n' ' ' 'f' 'o' 'x' ' ' 'j' 'u' 'm' 'p' 'e' 'd' ' ' 'o' 'v' 'e' 'r' ' ' 't' 'h' 'e' ' ' 'l' 'a' 'z' 'y' ' ' 'd' 'o' 'g']
input: "god yzal eht revo depmuj xof nworb kciuq ehT"
runes: ['g' 'o' 'd' ' ' 'y' 'z' 'a' 'l' ' ' 'e' 'h' 't' ' ' 'r' 'e' 'v' 'o' ' ' 'd' 'e' 'p' 'm' 'u' 'j' ' ' 'x' 'o' 'f' ' ' 'n' 'w' 'o' 'r' 'b' ' ' 'k' 'c' 'i' 'u' 'q' ' ' 'e' 'h' 'T']
original: "The quick brown fox jumped over the lazy dog"
reversed: "god yzal eht revo depmuj xof nworb kciuq ehT"
reversed again: "The quick brown fox jumped over the lazy dog"


<code>
f.Fuzz(func(t *testing.T, orig string) {
    rev := Reverse(orig)
    doubleRev := Reverse(rev)
    t.Logf("Number of runes: orig=%d, rev=%d, doubleRev=%d", utf8.RuneCountInString(orig), utf8.RuneCountInString(rev), utf8.RuneCountInString(doubleRev))
    if orig != doubleRev {
        t.Errorf("Before: %q, after: %q", orig, doubleRev)
    }
    if utf8.ValidString(orig) && !utf8.ValidString(rev) {
        t.Errorf("Reverse produced invalid UTF-8 string %q", rev)
    }
})
</code>

In [12]:
import (
    "testing"
    "unicode/utf8"
)

func FuzzReverse(f *testing.F) {
    testcases := []string{"Hello, world", " ", "!12345"}
    for _, tc := range testcases {
        f.Add(tc)  // Use f.Add to provide a seed corpus
    }
    f.Fuzz(func(t *testing.T, orig string) {
        rev := Reverse(orig)
        doubleRev := Reverse(rev)
        t.Logf("Number of runes: orig=%d, rev=%d, doubleRev=%d", utf8.RuneCountInString(orig), utf8.RuneCountInString(rev), utf8.RuneCountInString(doubleRev))
        if orig != doubleRev {
            t.Errorf("Before: %q, after: %q", orig, doubleRev)
        }
        if utf8.ValidString(orig) && !utf8.ValidString(rev) {
            t.Errorf("Reverse produced invalid UTF-8 string %q", rev)
        }
    })
}


In [13]:
!(cd fuzz;./reset2; go test)

input: "Hello, world"
input: " "
input: "!12345"
input: "Hello, world"
input: "dlrow ,olleH"
input: " "
input: " "
input: "!12345"
input: "54321!"
input: "餭\xe9\xa4\xc8"
input: "���餭"
input: "\U000d8410\U000d8410\U000d8410\U000d8410"
input: "\U000d8410\U000d8410\U000d8410\U000d8410"
input: "\x80"
input: "�"
input: "Ա"
input: "Ա"
--- FAIL: FuzzReverse (0.00s)
    --- FAIL: FuzzReverse/07778fbb547411fd (0.00s)
        reverse_test.go:32: Number of runes: orig=4, rev=4, doubleRev=4
        reverse_test.go:34: Before: "餭\xe9\xa4\xc8", after: "餭���"
    --- FAIL: FuzzReverse/98fce631eb9c5dd541458bf71a7241469a103001c64053f3a71625b41ccaea5f (0.00s)
        reverse_test.go:32: Number of runes: orig=1, rev=1, doubleRev=1
        reverse_test.go:34: Before: "\x80", after: "�"
FAIL
exit status 1
FAIL	example/fuzz	0.238s


exit status 1


In [14]:
!(cd fuzz;./reset2; go test -run=FuzzReverse/d5b6b60965e92e557798e88a10d04e5fb1070907a7dc6118b367e4fb501354bd)

input: "Ա"
input: "Ա"
PASS
ok  	example/fuzz	0.486s


In [15]:
!(cd fuzz; ./reset2; go test -fuzz="Fuzz")

input: "Hello, world"
input: " "
input: "!12345"
fuzz: elapsed: 0s, gathering baseline coverage: 0/50 completed
failure while testing seed corpus entry: FuzzReverse/07778fbb547411fd
fuzz: elapsed: 0s, gathering baseline coverage: 2/50 completed
--- FAIL: FuzzReverse (0.03s)
    --- FAIL: FuzzReverse (0.00s)
        reverse_test.go:32: Number of runes: orig=4, rev=4, doubleRev=4
        reverse_test.go:34: Before: "餭\xe9\xa4\xc8", after: "餭���"
    
FAIL
exit status 1
FAIL	example/fuzz	0.276s


exit status 1


In [16]:
!(cd fuzz;go test -run=FuzzReverse/98fce631eb9c5dd541458bf71a7241469a103001c64053f3a71625b41ccaea5f)

input: "\x80"
input: "�"
--- FAIL: FuzzReverse (0.00s)
    --- FAIL: FuzzReverse/98fce631eb9c5dd541458bf71a7241469a103001c64053f3a71625b41ccaea5f (0.00s)
        reverse_test.go:32: Number of runes: orig=1, rev=1, doubleRev=1
        reverse_test.go:34: Before: "\x80", after: "�"
FAIL
exit status 1
FAIL	example/fuzz	0.230s


exit status 1


### Fix the error

In [1]:
//package main

import (
    "errors"
    "fmt"
    "unicode/utf8"
)

func main() {
    input := "The quick brown fox jumped over the lazy dog"
    rev, revErr := Reverse(input)
    doubleRev, doubleRevErr := Reverse(rev)
    fmt.Printf("original: %q\n", input)
    fmt.Printf("reversed: %q, err: %v\n", rev, revErr)
    fmt.Printf("reversed again: %q, err: %v\n", doubleRev, doubleRevErr)
}

func Reverse(s string) (string, error) {
    if !utf8.ValidString(s) {
        return s, errors.New("input is not valid UTF-8")
    }
    r := []rune(s)
    for i, j := 0, len(r)-1; i < len(r)/2; i, j = i+1, j-1 {
        r[i], r[j] = r[j], r[i]
    }
    return string(r), nil
}

original: "The quick brown fox jumped over the lazy dog"
reversed: "god yzal eht revo depmuj xof nworb kciuq ehT", err: <nil>
reversed again: "The quick brown fox jumped over the lazy dog", err: <nil>


In [2]:
//package main

import (
    "testing"
    "unicode/utf8"
)

func FuzzReverse(f *testing.F) {
    testcases := []string{"Hello, world", " ", "!12345"}
    for _, tc := range testcases {
        f.Add(tc) // Use f.Add to provide a seed corpus
    }
    f.Fuzz(func(t *testing.T, orig string) {
        rev, err1 := Reverse(orig)
        if err1 != nil {
            return
        }
        doubleRev, err2 := Reverse(rev)
        if err2 != nil {
            return
        }
        if orig != doubleRev {
            t.Errorf("Before: %q, after: %q", orig, doubleRev)
        }
        if utf8.ValidString(orig) && !utf8.ValidString(rev) {
            t.Errorf("Reverse produced invalid UTF-8 string %q", rev)
        }
    })
}

In [3]:
!(cd fuzz; ./reset3; go test -fuzz="Fuzz" -fuzztime 30s)

fuzz: elapsed: 0s, gathering baseline coverage: 0/50 completed
fuzz: elapsed: 0s, gathering baseline coverage: 50/50 completed, now fuzzing with 10 workers
fuzz: elapsed: 3s, execs: 710933 (236930/sec), new interesting: 0 (total: 50)
fuzz: elapsed: 6s, execs: 1519662 (269610/sec), new interesting: 0 (total: 50)
fuzz: elapsed: 9s, execs: 2612252 (364126/sec), new interesting: 0 (total: 50)
fuzz: elapsed: 12s, execs: 3844676 (410782/sec), new interesting: 1 (total: 51)
fuzz: elapsed: 15s, execs: 4986876 (380770/sec), new interesting: 1 (total: 51)
fuzz: elapsed: 18s, execs: 6047822 (353655/sec), new interesting: 1 (total: 51)
fuzz: elapsed: 21s, execs: 7168621 (373647/sec), new interesting: 1 (total: 51)
fuzz: elapsed: 24s, execs: 8367548 (399678/sec), new interesting: 1 (total: 51)
fuzz: elapsed: 27s, execs: 9571315 (401249/sec), new interesting: 1 (total: 51)
fuzz: elapsed: 30s, execs: 10781133 (403283/sec), new interesting: 1 (total: 51)
fuzz: elapsed: 30s, execs: 10781133 (0/sec), ne